.github/workflows/dev.yml
.github/workflows/prod.yml
README.md
action.yaml
default.nix
makes.nix
makes/container-image/main.nix
src/cli.py
src/modules/outputs/builtins/deploy-container-image/default.nix
src/modules/outputs/builtins/format-bash/default.nix
src/modules/outputs/builtins/format-python/default.nix
src/modules/outputs/builtins/hello-world/default.nix
src/modules/outputs/builtins/lint-bash/default.nix
src/modules/outputs/custom.nix
src/modules/required-makes-version.nix

- Previously when buildint makes/main.nix
we used outputs."" which due to some
nix internals carry out the context of
all the outputs
- Now building makes/main.nix just builds
outputs."/" which prevents loading all
outputs

perf(build): remove context from default derivation

---

makes/main.nix

- It is required for evaluating projects with
flakes

feat(build): add git

---

README.md
makes/main.nix
src/cli/__main__.py

- Working over the git repository, with
tainted files and spurious outputs creates
irreproducibility
- Makes now will clone the HEAD of the repo
into an ephemeral folder
- This also introduces a cool side effect
of being able to run makes over remote
repositories by using M_FROM=repo m

feat(cross): ephemeral head

---

README.md
src/modules/outputs/builtins/lint-python/default.nix

- By making this name constant the dependencies
are shared in all generated lint scripts

perf(build): #29 cache hits

---

src/args/default.nix
src/args/fetchers/nixpkgs.nix
src/args/fetchers/url.nix
src/args/fetchers/zip.nix
src/modules/outputs/default.nix

- They do not require sha256 by default, but
obviously they will fail because the hash
does not coincide and thus still force
pinning dependencies. But it is way
more confortable this way

feat(build): #171 add fetchers

---

README.md
makes/nested/main.nix
src/args/make-search-paths/default.nix

- Make it not append an empty search path at the
end because it can be interpreted as the current
working directory (accidental impurity)
- Document with an example

feat(cross): #36 make search paths purity

---

src/cli/main/__main__.py

- When targetting a project in other directory
we must use absolute paths by joining the
src

fix(back): #188 relative paths

---

.github/workflows/release.yml

- Use the ephemeral github token as the secret no
longer exists

fix(build): #232 use ephemeral token

---

README.md
src/args/default.nix
src/args/lint-terraform/default.nix
src/args/make-secret-aws-from-env/default.nix
src/args/make-secret-aws-from-env/template.sh
src/args/shell-commands/makes-setup.sh
src/cli/main/__main__.py
src/evaluator/modules/default.nix
src/evaluator/modules/outputs/builtins/lint-terraform/default.nix
src/evaluator/modules/secrets.nix

- Allow in makes.nix to specify aws secrets from env
vars
- No secret values are dumped to the nix-store, of course.
Just env-var names (which are not secret)

feat(build): #252 aws secrets from env

---

makes/main.nix
src/args/default.nix
src/args/make-derivation/default.nix
src/cli/main/__main__.py

- After reading about the differences between all
ways to load paths, this one is the best:
- store path depends on content, not names
- handles unicode and illegal path names well
- generates a different store path per each
path instead of a big folder and references
to it
- it also allows to load the project lazily instead
of at startup

perf(build): #232 granular paths

---

src/args/default.nix

- Seems we need to load the entire HEAD otherwise
relative paths do not work

rever(build): #232 granular paths

---

src/args/default.nix
src/args/format-bash/default.nix
src/args/format-terraform/default.nix
src/args/paths-matching/default.nix
src/cli/main/__main__.py
src/evaluator/default.nix
src/evaluator/modules/outputs/builtins/format-markdown/default.nix
src/evaluator/modules/outputs/builtins/format-nix/default.nix
src/evaluator/modules/outputs/builtins/format-python/default.nix
src/evaluator/modules/outputs/builtins/lint-git-mailmap/default.nix

- Design the API for loading paths from the project
- Add pathCopy which copies the path and everything
under it to the store, useful for performance
- Keep path as it is
- Rename pathImpure to pathMutable, this name
represents better what it returns: a path
that you can modify in-place in the project
(used mostly for formatters)
- Remove all possible context from pathsMatching
so it returns bare strings

perf(build): #292 path functions

---

README.md
src/evaluator/default.nix

- Pining makes in other file allows for more
stability because it can be undependent of
the module system

feat(cross): #313 makes lock nix file

---

src/evaluator/default.nix

- Allow pining arguments too, we were using
the latest version bundled with the CLI

fix(build): #0 allow pining args too

---

src/args/default.nix
src/args/project-path/default.nix

- Make the root path not depend on the folder name,
which may vary from machine to machine

perf(build): #0 reproducibility of root

---

src/cli/main/__main__.py

- Execute post-build actions on the project,
instead of on the path the user invoked makes

feat(build): #374 execute actions on src

---

README.md
src/evaluator/modules/deploy-terraform/default.nix
src/evaluator/modules/lint-terraform/default.nix
src/evaluator/modules/taint-terraform/default.nix
src/evaluator/modules/test-terraform/default.nix

- Force terraform to be >= 0.14 in order to
prevent customers from using terraform versions
vulnerable to supply chain attacks

refac(build): #426 force tf 0.14

---

README.md
src/args/default.nix
src/args/make-python-environment/default.nix
src/args/make-python-pypi-mirror/builder.sh
src/args/make-python-pypi-mirror/check-completeness.py
src/args/make-python-pypi-mirror/default.nix

- Add a new argument that allows to mirror pypi
in a pure way, it works as a fixed-output derivation
and forces downloaded contents to be protected by a hash
- This allows us to enable sand-boxing and pure evaluation in Makes,
which is a feature we dropped by design a few years ago for keeping
things usable in the enterprise world

feat(build): #0 make python pypi mirror

---

README.md
src/args/default.nix
src/args/make-python-pypi-environment/builder.sh
src/args/make-python-pypi-environment/default.nix

- Add a new argument that allows to create
a virtual environment with packages from
pypi in a pure way (using fixed-output
derivations)
- This will allows us to enable sandboxing soon
(pending to migrate npm packages)

feat(build): #0 make python pypi env

---

src/args/from-yaml/default.nix

- Empty names are forbidden in nix 3

fix(build): #0 avoid empty names

---

src/args/make-secret-for-env-from-sops/template.sh

- Disable shopt xpg_echo
in make-secret-for-env-from-sops
as it breaks sops escaping

fix(back): #464 disable shopt

---

src/args/make-python-pypi-environment/default.nix

- Fetch with nixpkgs instead with the builtin,
maybe the builtin is bugged?

refac(build): #434 use nixpkgs fetch

---

src/args/make-python-pypi-environment/builder.sh
src/args/make-python-pypi-environment/default.nix

- Old versions of pip do not handle zips
with timestamps before 1980 well, later
versions does, so lets upgrade

fix(build): #434 upgrade pip

---

makes/utils/makePythonPypiEnvironmentSources/entrypoint.sh

- abi3 wheels are compatible with all python3 versions
- This allows to install cryptography without the rust
toolchain which is very cumbersome

feat(build): #434 include abi3

---

src/args/make-python-pypi-environment/default.nix

- For performance, dumping to yaml is non native
and therefore slow

refac(build): #0 allow non yaml sources

---

src/args/agnostic.nix
src/args/default.nix
src/args/make-node-js-environment-pure/builder.sh
src/args/make-node-js-environment-pure/default.nix

- I think we can package npm **purely** by turning package-lock.json
into a manifest with references to the nix store
- Start by nixifying the urls pointing at the
registry

feat(build): #494 prototype npm pkging

---

README.md
src/args/make-node-js-environment/default.nix
src/args/make-node-js-modules/default.nix

- For building special packages we need to
pass compilers down the road
- Add bash as bootstrapped dependency, it
is required many times

feat(build): #494 search paths

---

src/args/make-node-js-modules/builder.sh
src/args/make-node-js-modules/default.nix

- Make binaries executable as some of them
do not exist within .bin, causing permission
denied when executing symlinks
- Patch shebangs searching for node
in usr

fix(back): #449 patch shebangs

---

src/args/make-search-paths/default.nix

- builtins.pathExists only returns true if the path
exists at evaluation time, which may cause trouble
when testing paths existance on derivation outputs

refac(build): #0 handle runtime paths

---

README.md
src/args/make-node-js-environment/default.nix
src/args/make-node-js-modules/builder.sh
src/args/make-node-js-modules/default.nix

- Allow passing --ignore-scripts true to npm
- This allows to ignore setup scripts of dirty packages
like imagemin/mozjpeg-bin which have side effects for
downloading binaries from the internet which is not pure
and whose ELFs we don't need to patch

feat(build): #449 ignore scripts flag

---

README.md
makes.nix
src/evaluator/modules/default.nix

- Allow configuring the magic folder where
extensions live.
- This decouples people from where to place their code

feat(build): #0 magic makes folder

---

.mailmap
README.md
flake.nix
src/args/default.nix
src/evaluator/default.nix
src/evaluator/from-flake.nix

- Expose everything as packages, pending to see
how we can identify apps

feat(build): #546.1 packages

---

src/args/make-node-js-modules/default.nix

- Querying 2500 index.json gives the sensation
that it is not progressing
- By changing this name people will see in the logs
how 2500 different things are being computed,
which gives sensation of progress

refac(front): #0 use a name

---

.mailmap
README.md
src/args/make-script/default.nix
src/args/make-script/template.sh

- Add `persistState` to `makeScript` defaulting to `false`
- This default corresponds to the current behavior
- Enabling persistence should remain a mindful act

feat(build): #553 optionally persist script state

---

src/args/make-script/template.sh

- Add a builtin to makeScript family functions,
it was not added to shell builtins because
it does not make sense to prompt in a
makeDerivation, for example. So this function
is only available on runtime scripts

feat(build): #552 builtin prompt

---

src/args/project-path/default.nix

- `self.sourceInfo.outPath` brings a string context with it
- Drop it for this pattern to work
- Idempotent noop in non-flake scenario
fixes: #577 (has more context)
---
Appreciation to the really helpful support on matrix from
- abathur
- symphorien
- dee

fix projectPath string context flakes

---

flake.nix
src/evaluator/default.nix

- Make inputs now prime over flake inputs
- Rename to reflect this special purpose (& temporary) semantics of
this arg
fixes: #579

fix(build): #546 makes' inputs topple flakes'

---

README.md
default.nix
makes.nix
src/args/agnostic.nix
src/args/default.nix
src/args/make-script/default.nix
src/args/make-script/template.sh
src/evaluator/default.nix
src/evaluator/modules/default.nix

- Introduces `projectIdentifier`, `globalStateDir` & `projectStateDir`
- `globalStateDir` defaults to `${HOME_IMPURE}/.makes/state` (as is)
- `projectStateDir` defaults to `globalStateDir` if `projectIdentifier`
is not specified. Makes all state effectively global.
- Both, `globalStateDir` & `projectStateDir` can also be manually set.
- In that case, `projectIdentifier` is not used for project state.
- `projectIdentifier` is independently useful in future, e.g. for
logging.
---
```diff
```
-> `nix run . -- . /lintGitMailMap`
```console
❯ tree ~/.makes/state
/home/blaggacao/.makes/state
└── makes-repo
└── lint-git-mailmap-for-lint-git-mailmap
```
-> `rm -rf ~/.makes/state/makes-repo`
---
```diff
diff --git a/makes.nix b/makes.nix
index 9cfe124..da5ddd6 100644
--- a/makes.nix
+++ …
```

feat(build): #553 global state across repositories

---

makes/tests/scriptWithHelp/README.md
makes/tests/scriptWithHelp/main.nix
src/args/agnostic.nix
src/args/make-derivation/default.nix
src/args/make-script-parallel/default.nix
src/args/make-script/default.nix
src/args/make-template/default.nix

- Enable derivations to contain help as markdown
- Show help on all actions with `--help | -h` if help is set
- Show that help with `glow`
Why Markdown:
- needs to look good on github and cli
- github cli uses glow's library for `gh repo info`
- glow's library is md only
- among markup languages, md is the best known and most familiar one
---
- This is probably a good enough platform to venture into the frontmatter aspects as discussed in https://github.com/fluidattacks/makes/issues/521#issuecomment-922387563 ff. 
- Docs tbd after design accepted
- change `glow` for https://kristaps.bsd.lv/lowdown/ (used by `nix`)

feat(build): #521 standard for derivation help

---

README.md
src/cli/main/__main__.py

- This allows us to remove projectPathMutable,
see why
- When running a remote project, it makes
sense to be able to run it from anywhere in the
file system, and therefore CWD is the intuitive choice.
This allows the following use case:
someone offer a jpg to png binary,
users of such project can run it like this:
`m github:... /jpg2png ./x ../y`, where
x and y are relative to its current location.
- The option to run projects located in other
places than the current folder has been removed.
it's counter-intuitive, and it introduces the need
for a projectPathMutable, which is not available
on future releases of nix
- When running a project in the current working
directory, it's because with all probability I'm a dev
and I want to format my code, run some tests, or test
binaries out, …

refac(build): #598 run scripts on cwd

---

.github/workflows/prod.yml
README.md
default.nix
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

- Now 21.10 becomes the stable release,
the version people should use on their production systems
- 21.11 becomes the unstable release,
an alias to `main`,
where we push changes daily
and in backward incompatible ways when needed
- Thank you so much to the people that contributed
in different ways to make this release possible:
issues, feature requests, feedback, using it, github stars,
and special thanks to the people that contributed code
so other people around the world could use it.
I firmly believe that we achieve more together!

refac(cross): #0 bump to 21.11

---

.mailmap
makes.nix
src/evaluator/modules/default.nix
src/evaluator/modules/format-javascript/default.nix
src/evaluator/modules/format-javascript/entrypoint.sh
src/evaluator/modules/format-javascript/settings-prettierrc.yaml

use pettier to format code, pettier allows to format the
following languages
- JavaScript
- JSX
- Angular
- Vue
- Flow
- TypeScript
- CSS, Less, and SCSS
- HTML
- JSON
- GraphQL
- Markdown
- YAML

feat(build): #524 add javascript formatter

---

src/cli/main/__main__.py

- Persist outputs symlinks on ~/.makes folder

feat(build): #0 persist outputs

---

.mailmap
src/evaluator/modules/default.nix
src/evaluator/modules/format-scala/default.nix
src/evaluator/modules/format-scala/entrypoint.sh

- i decided not to use `nixpkgs.scalafmt` because it uses an old version (v2.6.4)
- `nixpkgs.scalafmt` compiles on site, this makes longer dependencies
- i download the binary and `java-jdk` is not required

feat(back): #753.1 add scala formatter

---

src/evaluator/modules/dynamodb/default.nix

- some arguments can be taken from places where the source
code might not be available (ks8)
- a copy of the data is required and not a reference to the
current location

feat(build): #683 take arguments as project path

---

src/evaluator/modules/deploy-nomad/default.nix

error output: 
```
A definition for option `deployNomad.jobs.job2.namespace' is not of type `path'. Definition values:                      
- In `<unknown-file>': "default" 
```
fixed output:

fix(build): deployNomad namespace type

---

.github/workflows/prod.yml
README.md

- Remove permissions for production yaml

fix(build): #831 deployments

---

src/args/to-file-yaml/default.nix

- Add default header in toFileYaml builtin

feat(back): #882 yaml header

---

README.md
src/args/make-secret-for-aws-from-gitlab/default.nix
src/args/make-secret-for-aws-from-gitlab/template.sh
src/evaluator/modules/secrets-for-aws-from-gitlab/default.nix

- Support retries in secrets for aws from gitlab

feat(back): #889 support retries

---

makes.nix
src/cli/main/__main__.py

- Create a Config composite type
- Split main function into some steps
- The reason for this change is that
we are just at the limit of the length
of the `cli` function and I cannot add
any more code without the linter yelling at me

refac(back): #894 split function

---

src/cli/main/__main__.py

- Generate some basic fields of provenance that
are easy to collect from the environment

feat(back): #894 generate provenance

---

src/cli/main/__main__.py

- Add a better source identifier
- Fix the entrypoint and parameters
- Make the provenance have .json extension

feat(back): #894 data quality

---

src/cli/main/__main__.py

- The previous environment variable may contain a temporary user and password generated by gitlab while clonning the repository, so lets use another variable witohut it

feat(back): #894 use repo url

---

src/args/lint-python/pypi-deps.yaml
src/args/lint-python/pypi-sources-3.10.yaml
src/args/lint-python/pypi-sources-3.8.yaml
src/args/lint-python/pypi-sources-3.9.yaml

- Update indirect dependencies
- Pin pylint
- Add a missing file for python 3.10, which didn't failed because of Nix laziness but would fail if somebody invokes it

feat(back): #0 refresh lint-python deps

---

README.md
src/args/secure-kubernetes-with-rbac-police/default.nix
src/args/secure-kubernetes-with-rbac-police/entrypoint.sh

- Patch rbac-police binary so it uses nixpkgs glibc ld-linux
- This fixes the job on containers
- Stop supporting darwin due to the patch

fix(back): #909 container executions

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
default.nix
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

- In september 2022 (22.09), the 22.09 tag, release and container, should be the stable version of Makes, and the 22.10 tag, release and container should be the unstable version.
All development that happens during september 2022, should go to the 22.10 tag, release and container, because the docs promise that: "the current month release is frozen", so we shouldn't be modifying 22.09.

fix(cross): #0 versioning scheme

---

docs/src/SUMMARY.md
docs/src/architecture/README.md

- Add an architecture diagram to the docs

feat(doc): #919 architecture diagram

---

makes/docs/dev/entrypoint.sh
makes/docs/dev/main.nix

- Add a docs development enviornment, just run and open localhost:3000

feat(build): #919 docs dev env

---

docs/src/SUMMARY.md
docs/src/security/README.md
docs/src/security/threat-model.md

- Start documenting the threat model of Makes

feat(doc): #919 threat model

---

docs/src/security/threat-model.md

- Document a repudiation threat

feat(doc): #919 repudiation threat

---

docs/src/security/design-principles.md

- Write an argument on how we comply the secure design principles

feat(doc): #919 design principles

---

docs/src/SUMMARY.md
docs/src/security/threat-model.md

- Write an information disclosure threat and how we mitigate it

feat(doc): #919 info disclosure

---

docs/src/security/threat-model/README.md
makes/cli/env/runtime/main.nix
src/cli/main/cli.py

- Include openssh in the makes CLI, so that people can fetch private repositories
- Document this in the threat model, their possible dangers, and mitigation

feat(build): #941 include openssh

---

makes/container-image/builder.sh
makes/container-image/main.nix

- We cannot make the container fully non-root, but we can make makes run as makes.
- Expose this feature under a feature flag, since it has a small performance hit at the beginning while chown-ing /nix and also allowing us to test this without much risk

feat(build): #944 doas make

---

makes/container-image/main.nix

- Point user vars to their right place,
- `doas -u makes` already updates USER and HOME to the makes values

feat(build): #944 user vars

---

.github/workflows/prod.yml
src/args/format-yaml/default.nix
src/args/format-yaml/entrypoint.sh

- Use prettier as yaml format, this way we can embed it on vscode easily

feat(back): #0 use prettier

---

.github/workflows/dev.yml
.github/workflows/dev.yml.license
.github/workflows/prod.yml
.github/workflows/prod.yml.license
.github/workflows/scorecards-analysis.yaml
.github/workflows/scorecards-analysis.yaml.license

- Pin actions to a commit hash

feat(build): #919 pin github actions

---

makes/container-image/main.nix

- After changing users, the git directory endup being owned by a different user

feat(build): #944 git safe directory

---

makes/container-image/main.nix

- Use an empty working dir, instead of /, so that we can chown-it to the unprivileged user

feat(build): #944 working dir not /

---

makes/container-image/main.nix

- This way the exit code is propagated from the makes job

fix(build): #944 rm last set -x

---

README.md
src/args/agnostic.nix
src/args/chunks/default.nix
src/args/sublist/default.nix

- Add builtin for splitting a list into several N chunks
- Add builtin for creating a list sublist based on starting and ending indexes
- Add doc for both builtins
Signed-off-by: Daniel Salazar <podany270895@gmail.com>

feat(back): #995 new builtins

---

README.md
makes/utils/makeRubyLock/entrypoint.sh
makes/utils/makeRubyLock/main.nix
makes/utils/makeRubyLock/parser.rb
src/args/make-ruby-version/default.nix

- Add make ruby lock builtin
- Add support for Ruby 3.1
- Remove support for Ruby 2.6
- Update doc

feat(back): #997 make ruby lock

---

README.md
makes/cli/env/runtime/main.nix
src/cli/main/cli.py

- attic is not a cache solution that we should use, it does not solve anything that cachix cannot do

refac(build): #1007 remove attic logic

---

docs/mkdocs.yaml

- Implement analytics
- Implement cookie consent
- Implement social links
- Improve navigation

feat(doc): #940 analytics

---

docs/src/api/builtins/lint.md
docs/src/api/builtins/security.md
docs/src/api/extensions/format-conversion.md

feat(doc): #940 missing admonitions

---

docs/src/api/extensions/node.js.md
src/args/make-node-js-modules/default.nix

- Remove unnecessary condition over `isLinux`

refac(back): #1045 remove islinux

---

src/evaluator/modules/lint-git-commit-msg/default.nix

- The linter is usable in macOS, the `isLinux` verification is not needed

refac(back): #1045 update commit linter

---

docs/src/api/builtins/lint.md

- `lintGitCommitMsg` is now usable in macOS

refac(doc): #1045 update docs

---

.github/workflows/prod.yml
makes.nix

- Use bigger buildjet runners
- Do not sign arm containers for testing purposes

feat(build): #1064 bigger buildjet runners

---

docs/src/api/extensions/python.md
src/args/lint-python-imports/default.nix
src/args/lint-python/default.nix
src/args/make-python-pypi-environment/default.nix

- now using up to date versions of setuptools and wheel

fix(back): #1070 update python linter deps

---

docs/src/api/builtins/lint.md
src/args/lint-markdown/builder.sh
src/args/lint-markdown/default.nix
src/evaluator/modules/lint-markdown/default.nix
src/evaluator/modules/lint-markdown/rulesets.rb

- Add a new parameter --rulesets to the lintMarkdown linter implementation, which allows passing the file with custom rules for Markdownlint.
- Add a new default rulesets.rb file
- Update lintMarkdown builtin documentation

feat(back): #1087 enable custom rulesets for the lintMarkdown builtin

---

src/cli/main/cli.py
src/evaluator/default.nix
src/evaluator/modules/default.nix

- Collect attr paths using python globs for initialization performance
- Pass them as attrPaths to evaluator
- Redefine evaluator logic for building outputs from attrs
- Initialization for universe takes less than 3 seconds now

feat(back): #1101 globbed attrs

---

docs/src/contributing.md
test/lint-markdown/config.rb

Add new sections to the contributing.md file to help newcomers.
- Running your local changes
- Adding yourself to the mailmap
- Validating commit message
- DCO
- Adding and rendering documentation

feat(build): #1108 document contributing

---

src/evaluator/modules/default.nix

- Stop checking if path exists as it was collected a few milliseconds ago
- Only declare some trivial variables once

perf(back): #1101 faster init

---

docs/src/api/builtins/test.md
makes.nix
src/evaluator/modules/test-license/default.nix

- fix `testLicense` still appears when there are no references.

feat(build): #1099 fix testlicense bug

---

.mailmap
src/args/make-template/default.nix
src/args/manage-ports/default.nix
src/args/manage-ports/template.sh

- default import of `shellCommands` builtin in `makeTemplate`

fix(build): #1002 args manage ports fix

---

makes/cli/env/runtime/main.nix
src/cli/main/cli.py

- Make _nix_hashes receive bytes so it is compatible with stdin
- Make _nix_hashes process provided paths using xargs to avoid hitting ARG_MAX limit
- Add findutils to runtime so xargs is available

feat(back): #1128 avoid hitting max arg limit

---

makes.nix

- replace `inputs.nixpkgs` with `__nixpkgs__` at `/makes.nix`

feat(build): #1097 deprecate inputs.nixpkgs

---

docs/src/api/extensions/python.md
src/args/agnostic.nix
src/args/make-python-pyproject-package/default.nix
src/args/make-python-pyproject-package/generic_builder/check.nix
src/args/make-python-pyproject-package/generic_builder/default.nix
src/args/make-python-pyproject-package/generic_builder/env.nix
src/args/make-python-pyproject-package/generic_builder/metadata.nix
src/args/make-python-pyproject-package/generic_builder/pkg/check/tests.sh
src/args/make-python-pyproject-package/generic_builder/pkg/check/types.sh
src/args/make-python-pyproject-package/generic_builder/pkg/default.nix
src/args/python-override-utils/default.nix

- add make-python-pyproject buiding from nixpkgs functions
- add python-override-utils

feat(back): #1146 make python pyproject

---

src/args/make-python-pypi-environment/default.nix

- Add `--fail` to retry on HTTP 5XX response code (`curl: (35) Send failure: Connection reset by peer`)

feat(build): #1126 retry makepythonpypienvironment

---

.github/workflows/dev.yml
src/cli/main/cli.py

- remove _add_safe_directory function

feat(build): #979 remove _add_safe_directory

---

docs/src/api/extensions/python.md
src/args/agnostic.nix
src/args/make-python-vscode-settings/default.nix
src/args/make-python-vscode-settings/template.sh
src/args/make-python-vscode-settings/vs_settings.py
src/args/python-override-utils/default.nix

- adjust python docs
- add makePythonVscodeSettings util
- fix pythonOverrideUtils compose

feat(back): #1168 python vscode settings

---

.mailmap
makes/utils/makePythonLock/entrypoint.sh
src/args/make-python-vscode-settings/default.nix
src/args/python-override-utils/default.nix

- add exclusion for win_arm64 wheels inside makePythonLock
- exclude packages without links from the sources.yaml

refac(back): #1172 ignore win-arm64 wheels

---

src/args/lint-python/builder.sh
src/args/project-path/default.nix

- Add support for hidden files in root when using projectPath
- Adapt lintPython to support new directory names
Signed-off-by: Daniel Salazar <podany270895@gmail.com>

feat(back): #1200 support hidden files in root

---

src/args/lint-python/builder.sh

- Use last directory in path as module name in order to avoid breaking the builtin

fix(back): #1200 module name

---

src/args/lint-python/builder.sh
src/args/project-path/default.nix

- Keep using basename in order to avoid errors
- Remove prefix dot if basename contains it
- get package_name the old way

refac(back): #1200 remove prefix

---

makes/utils/makeNodeJsLock/entrypoint.sh
src/args/lint-git-commit-msg/default.nix
src/args/lint-with-ajv/default.nix
src/evaluator/modules/format-markdown/default.nix

feat(build): #1043 support nodejs 18

---

docs/src/api/builtins/utilities.md
makes/utils/makeNodeJsLock/entrypoint.sh

- `makeNodeJsLock` now receives the directory that contains the `package.json` file instead of the `package.json` file itself.
- The `package-lock.json` file will be generated in the same directory that contains the `package.json` file.
- `makeNodeJsLock` now only receives two parameters: `node_js_version` and `package_json_dir`.
- Removed `package_lock` parameter from `makeNodeJsLock`.
- Updated `makeNodeJsLock` documentation.

feat(build): #1212 upgrade makenodejslock parameters

---

docs/src/api/builtins/utilities.md
makes/docs/runtime/main.nix
makes/utils/makeNodeJsLock/entrypoint.sh
makes/utils/makeNodeJsLock/main.nix
makes/utils/makeRubyLock/entrypoint.sh
makes/utils/makeRubyLock/main.nix
src/args/agnostic.nix
src/args/make-node-js-version/default.nix
src/args/make-ruby-version/default.nix
src/nix/sources.json

- Update nixpkgs to last version

feat(build): #1202 update nixpkgs

---

makes/main.nix
src/cli/main/cli.py
src/evaluator/default.nix
src/nix/sources.json

- This reverts commit 932796834be608f3dddfc1c128ffda161ef653c0.

rever(back): #1202 pin nix version

---

.github/workflows/prod.yml
docs/src/api/builtins/utilities.md
docs/src/getting-started.md
docs/src/versioning.md
makes.nix
makes/cli/env/runtime/main.nix
makes/main.nix
src/cli/main/cli.py
src/evaluator/default.nix
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

- Release new major version
- This version will incorporate breaking changes brought after nixos 25.05
- Stop supporting nix unstable in CLI
- Pin nix to 2.15

feat(back): #1202 new major

---

.gitignore
docs/src/api/extensions/node.js.md
docs/src/api/extensions/ruby.md
makes/utils/makeRubyLock/entrypoint.sh
src/args/lint-git-commit-msg/commitlint/package-lock.json
src/args/lint-git-commit-msg/commitlint/package.json
src/args/lint-with-ajv/ajv-cli/package-lock.json
src/args/lint-with-ajv/ajv-cli/package.json
src/args/make-node-js-environment/default.nix
src/args/make-node-js-modules/builder.sh
src/args/make-node-js-modules/default.nix
src/args/test-pull-request/package-lock.json
src/args/test-pull-request/package.json
src/evaluator/modules/format-markdown/doctoc/package-lock.json
src/evaluator/modules/format-markdown/doctoc/package.json

- Use node2nix for building node modules
- Update locks to include name as it is now required by node2nix

feat(cross): #1043 use node2nix

---

src/args/make-ruby-gems-environment/default.nix

- Deprecate `makeRubyVersion` from `makeRubyGemsEnvironment`

feat(back): #1249 deprecate makerubyversion

---

.mailmap
src/args/make-python-environment/default.nix

- Update mailmap
- Set `HOME` to a temp dir
- Remove `homeless-shelter` dir if it exists
- Create external function to fetch all packages
names from a TOML file, including the extras
Approach:
- Read the TOML file and get the packages.
- Override the `preUnpack` function to set
`HOME` to a temp dir.
- Override the `overrides` function to combine,
in case of conflict, the `overrides` that was passed
will be the one that prevails.

feat(build): #1282 assure purity removing dir

---

src/cli/main/__main__.py
src/cli/main/cli.py

- both in subprocess and main
- to catch the case where the tui hasn't even started yet

feat(build): #970 handle keyboard interrupt

---

docs/src/api/builtins/utilities.md
makes/utils/makeNodeJsLock/entrypoint.sh

- Update makeNodeJsLock utility to support the lock_file version

refac(cross): #1290 update makenodejslock

---

src/args/lint-python-imports/default.nix

- Add a `preUnpack` hook to the `grimp` derivation to set the `HOME` environment variable to a
temporary directory and remove the `/homeless-shelter` directory.

feat(build): #1293 fix homeless shelter issue

---

docs/src/api/extensions/fundamentals.md
docs/src/api/extensions/python.md

- Add note about homeless-shelter in the python extension documentation to make sure that the user knows that we delete this directory and change the `HOME` variable to assure purity of builds without sandboxing.

feat(docs): #1296 add note about homeless-shelter

---

docs/src/api/builtins/deploy.md
docs/src/api/extensions/containers.md

- past "OIDC keyless approach" url was deprecated, new url points to the new documentation
- past "OCI Runtime Configuration Manifest" url was wrong (the ".md" extension was missing) and fixed url points to a message that announce that documentation was moved to a separate repository

fix(doc): #1304 fix broken urls

---

.mailmap
docs/mkdocs.yaml

- since the site name is being added to the title tag in each
page, we should keep it simple to
avoid warnings

fix(doc): #1304 update site_name

---

src/args/lint-python/builder.sh
src/args/lint-python/poetry.lock
src/args/lint-python/pyproject.toml

- Use mypy instead of dmypy, dmypy was causing issues with the CI.
- Upgrade mypy to 1.9.0

feat(back): #1298 upgrade mypy

---

docs/src/api/builtins/lint.md
src/args/lint-git-mailmap/default.nix
src/args/lint-git-mailmap/entrypoint.sh
src/evaluator/modules/lint-git-mailmap/default.nix

- Upgrade to the latest version of mailmap-linter
- Add a `exclude` option to the lint-git-mailmap module
- Add a `--exclude` option to the entrypoint script

feat(back): #1314 upgrade lint-git-mailmap

---

docs/src/security/assurance.md

- update docs to show continuous hacking certification instead of dependabot

refac(doc): #1304 update doc

---

makes/utils/makeNodeJsLock/entrypoint.sh

- add `--package-lock-only` to `npm install` command
- fix default value for `lockfile_version` in `entrypoint.sh`

feat(back): #1317 fix makenodejslock

---

docs/src/api/builtins/lint.md
makes.nix
src/evaluator/modules/lint-python/default.nix

- Fix typo in lintPython attribute `dirsOfModules` to `dirOfModules`.

feat(back): #1347 fix lintpython typo

---

makes/docs/runtime/pypi/poetry.lock
makes/docs/runtime/pypi/pyproject.toml

- Update certifi from 2024.6.2 (vulnerable) to 2024.7.4

feat(doc): #1349 update vuln dependency

---

src/args/deploy-container/entrypoint.sh

- Adapt cosign command to avoid storing sensitive data
in disk

refac(back): #1351 adapt cosign

---

.github/workflows/prod.yml
docs/src/api/builtins/deploy.md
docs/src/getting-started.md
makes.nix
src/args/deploy-container/entrypoint.sh
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

- Deploy multi-arch container on `fluidattacks/makes:latest`
- Stop using arch-based registries in favor of the root one
- Remove unnecessary CI jobs
- Update documentation on recommended makes container

feat(back): #1351 multi-arch container

---

.github/workflows/prod.yml

- Use amd64 nixos image for pushing multi-arch manifest

fix(build): #1351 amd64 nixos image

---

docs/src/api/builtins/deploy.md
makes.nix
src/args/deploy-container-manifest/default.nix
src/evaluator/modules/deploy-container-manifest/default.nix

- Remove config parameter in favor of a more flat approach

refac(back): #1364 remove config

---

.github/workflows/prod.yml
docs/src/api/builtins/deploy.md
docs/src/api/builtins/utilities.md
docs/src/getting-started.md
docs/src/versioning.md
makes.nix
makes/main.nix
src/cli/main/cli.py
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

- Add new 24.09 pre-release version
- Make 24.02 stable version

feat(back): #1364 new version

---

docs/src/api/builtins/deploy.md
makes.nix
src/args/deploy-container/default.nix
src/args/deploy-container/entrypoint.sh
src/evaluator/modules/deploy-container/default.nix

- Make it simpler and consistent with deployContainerManifest
- Remove `images` option in favor of a flat approach
- Remove attempts logic for simplicity

refac(back): #1364 simplify deploy container

---

makes/container-image/main.nix

- Deprecate functionality in order to keep makes simple and bring back a single binary

refac(back): #1357 deprecate makes non root

---

docs/src/security/design-principles.md
src/cli/main/cli.py

- Deprecate sandbox option from CLI as it only works on privileged containers
or machines with multi-user nix with
a trusted user executing makes.
Ideally deciding whether or not to use sandbox
should be done by the user via nix.conf.
- Deprecate MAKES_K8S_COMPAT as it is only used for disabling sandbox,
which is now done by the user via nix.conf.
- Update design principles

refac(back): #1354 deprecate sandbox

---

README.md
docs/mkdocs.yaml
docs/src/contributing.md
makes/docs/deploy/entrypoint.sh

- Update domain to fluidattacks.tech in README.md, mkdocs.yaml, contributing.md and
entrypoint.sh

feat(doc): #1375 update domain to fluidattacks.tech

---

src/args/agnostic.nix
src/args/make-secret-for-aws-from-gitlab/default.nix
src/args/make-secret-for-aws-from-gitlab/template.sh
src/evaluator/modules/default.nix
src/evaluator/modules/secrets-for-aws-from-gitlab/default.nix

- Recover secretsForAwsFromGitlab as it is currently being used

refac(back): #1378 recover builtin

---

.gitignore
.mailmap
src/cli/main/cli.py

- Support experimental-features on makes

feat(back): #1432 support experimental-features
