default.nix
makes/main.nix
src/args/builtin/lambdas.nix
src/args/builtin/shell-commands.sh
src/args/builtin/shell-options.sh
src/args/make-derivation/default.nix
src/cli.py
src/default.nix

- We can now actually build stuff, it works!
- Will extend this basic functions until we get to where
we are used to

feat(cross): working basic derivation

---

makes/main.nix
src/args/builtin/shell-commands.sh
src/args/make-derivation/default.nix
src/args/make-entrypoint/builder.sh
src/args/make-entrypoint/default.nix
src/args/make-entrypoint/template.sh
src/args/make-search-paths/default.nix
src/args/make-template/builder.sh
src/args/make-template/default.nix
src/default.nix

- Support completely makeDerivation, makeTemplate and makeEntrypoint

feat(cross): full support for building blocks

---

default.nix
src/cli.py

- It now can list the available attributes
to build

feat(font): re-write the cli

---

src/cli.py

- Now if no arguments are passed we will
try to list project outputs
- Handle errors at the top level, so the
tool never explodes on the customer face

feat(back): error handling

---

makes/main.nix

- These are required to unpack .tar.gz nixpkgs

fix(build): #25 missing deps

---

action.yaml

- Seems the name has been taken

feat(conf): rename action

---

action.yaml
makes.nix

- Giving people the possibility to pin their makes
is important, with this we are giving them that

feat(conf): head and montly release

---

.github/workflows/release.yml

- It is not working so lets try other possibilities:
- Add the secret as env var
- Use a slash to reference the file

fix(job): secrets as env var

---

README.md

- The github action takes care of it

fix(doc): remove unnecesary header

---

README.md
src/cli.py
src/modules/outputs/custom.nix

- People only require this when they want to
extend makes

feat(cross): optional makes folder

---

README.md
action.yaml
makes.nix

- Explain which version is stable, which one
unstable, so people get maximum stability
from makes

feat(cross): versioning skims

---

.github/workflows/release.yml
README.md
action.yaml

- It is important for people to be able to pin
their makes version, with this we walk
towards that goal

feat(cross): tag makes releases

---

src/args/make-script/builder.sh

- I was overriding the file, we need to append

fix(build): command aliases

---

README.md
action.yaml
default.nix
makes.nix
src/modules/required-makes-version.nix

- So a tag is created and people can reference it

feat(conf): bump pre-release

---

src/modules/outputs/builtins/default.nix
src/modules/outputs/builtins/lint-bash/default.nix
src/modules/outputs/builtins/lint-bash/entrypoint.sh

feat(back): bash lint util

---

.github/workflows/prod.yml

perf(build): separate jobs

---

.github/workflows/release.yml

- currently tags and releases are fixed, this
should update them

feat(build): create or update tag and release

---

.github/workflows/dev.yml
.github/workflows/prod.yml
.github/workflows/release.yml

- The tutorial said 1.0, but it should be 1.0.0

fix(build): use correct action version

---

.github/workflows/prod.yml
.github/workflows/release.yml

feat(build): disable prod and release jobs

---

.github/workflows/dev.yml
README.md
makes.nix

feat(cross): lint bash

---

src/args/make-python-environment/builder.sh
src/args/make-python-environment/default.nix
src/modules/outputs/default.nix

- ![image](https://user-images.githubusercontent.com/47480384/124808792-feb4a380-df24-11eb-99ff-b9eea4b0a441.png)
- ![image](https://user-images.githubusercontent.com/47480384/124808843-12600a00-df25-11eb-8dc1-4318447e7fab.png)

feat(build): #125 make python environment

---

src/args/make-python-environment/default.nix

- Now it returns a sourceable script to
activate the dependencies, instead of
a raw folder that people would have
then setup in ugly ways

feat(build): #125 source-able output

---

makes.nix
src/args/make-derivation/default.nix
src/args/make-script/default.nix
src/args/make-template/default.nix
src/modules/assertions.nix
src/modules/default.nix
src/modules/outputs/builtins/default.nix
src/modules/outputs/builtins/deploy-container-image/default.nix
src/modules/outputs/builtins/lint-nix/default.nix
src/modules/outputs/builtins/lint-nix/entrypoint.sh
src/modules/outputs/custom.nix
src/modules/outputs/default.nix
src/nix/sources.nix

- Add base job
- Adapt all nix files except sources.nix

feat(build): lint nix

---

makes.nix
src/modules/outputs/builtins/default.nix
src/modules/outputs/builtins/format-nix/default.nix
src/modules/outputs/builtins/format-nix/entrypoint.sh

feat(build): nix formatter

---

makes/main.nix
src/cli/__main__.py

- This way we can lint it in an isolated way
and also improve cache hits

refac(build): #29 move cli into own module

---

.github/workflows/dev.yml
README.md

- Add doc for formatNix
- Add loc for lintNix
- ADd jobs to CI

feat(cross): nix linter and formatter

---

src/args/make-node-environment/builder.sh
src/args/make-node-environment/default.nix
src/modules/outputs/default.nix

feat(build): #138 make node env

---

makes.nix
src/args/make-node-environment/default.nix
src/modules/outputs/builtins/default.nix
src/modules/outputs/builtins/lint-commit-msg/default.nix
src/modules/outputs/builtins/lint-commit-msg/entrypoint.sh

- Add job
- Minor changes to make node environment

feat(build): #138 lint commit msg

---

makes.nix
src/args/make-script/template.sh
src/modules/outputs/builtins/format-bash/entrypoint.sh
src/modules/outputs/builtins/format-python/entrypoint.sh
src/modules/outputs/builtins/lint-commit-msg/default.nix
src/modules/outputs/builtins/lint-commit-msg/entrypoint.sh

- Add a funcion available in all Makes
for testing when we are running in the
ci/cd provider, instead of in the dev
machine

feat(build): #146 centralize is in ci logic

---

.github/workflows/dev.yml
README.md
src/modules/outputs/builtins/lint-commit-msg/config.js
src/modules/outputs/builtins/lint-commit-msg/default.nix
src/modules/outputs/builtins/lint-commit-msg/entrypoint.sh
src/modules/outputs/builtins/lint-commit-msg/parser.js

- Add commitlint parser preset
- Add commitlint rules
- Add doc
- Turn on job

feat(cross): #138.3 commitlint config

---

README.md

- Update docs to reflect changes on lintPython

feat(doc): #29 update docs

---

README.md
src/modules/outputs/builtins/lint-python/default.nix

- Add the posibility to inject dependencies into the
environment

feat(cross): #29 extra sources

---

src/modules/outputs/builtins/lint-python/default.nix

- Subdependencies vary according to the interpreter used

feat(build): #29 subdependencies

---

README.md

- Add some words about this argument

feat(doc): #36 search paths skeleton

---

src/modules/outputs/builtins/lint-bash/builder.sh
src/modules/outputs/builtins/lint-bash/default.nix

feat(build): #161 derivation for lint bash

---

src/modules/outputs/builtins/lint-nix/builder.sh
src/modules/outputs/builtins/lint-nix/default.nix

feat(build): #161 derivation for lint nix

---

makes.nix
src/modules/outputs/builtins/default.nix
src/modules/outputs/builtins/lint-markdown/builder.sh
src/modules/outputs/builtins/lint-markdown/default.nix
src/modules/outputs/builtins/lint-markdown/style.rb

feat(build): #158 markdown linter

---

.github/workflows/release.yml
README.md
src/modules/outputs/builtins/lint-markdown/style.rb

- Adapt readme to linter
- Update style
- Update commit msg for toc

refac(front): #158 adapt readme

---

.github/workflows/release.yml
README.md
src/modules/outputs/builtins/lint-markdown/style.rb

This reverts commit ab2eb82aef0feb38171d602c5df020364635e0aa.

rever(front): #158 adapt readme

---

.github/workflows/dev.yml
README.md

feat(cross): #158 add doc

---

README.md

feat(doc): #36 extend make search paths

---

src/cli/main/__main__.py

- Propagate modified files tracked by git
in order to make developing more intuitive,
but still removing unwanted files from the
build

feat(back): #172 propagate modified files

---

justfile

- This allows to execute a dev version of makes

feat(build): #172 add a justfile

---

justfile
src/nix/sources.json

feat(build): #171 update nixpkgs

---

.github/workflows/dev.yml
justfile
src/cli/main/__main__.py
src/modules/outputs/builtins/__all__/default.nix
src/modules/outputs/builtins/default.nix

- So one can test building all attributes,
useful for touching the entire build system
arch

feat(build): #171 add hidden __all__ output

---

README.md
src/cli/main/__main__.py
src/modules/outputs/builtins/lint-markdown/builder.sh

- Exit with the exit code of the built derivation

fix(back): #171 propagate exit codes

---

README.md
makes.nix
makes/main.nix
src/args/default.nix
src/evaluator.nix

- Try to centralize them so we can re-use, the thing
is a little bit coupled so lets untie the knot

refac(build): #171 clean arguments propagation

---

src/evaluator.nix
src/modules/default.nix
src/modules/outputs/default.nix

- Now args is only imported once, code is more readable

refac(build): #171 import args only once

---

README.md
makes.nix
makes/container-image/main.nix
makes/main.nix
src/args/builtin/lambdas.nix
src/args/default.nix
src/args/deploy-container-image/default.nix
src/args/fetchers/nixpkgs.nix
src/args/fetchers/url.nix
src/args/fetchers/zip.nix
src/args/make-container-image/default.nix
src/args/make-derivation/default.nix
src/args/make-node-environment/default.nix
src/args/make-parallel/default.nix
src/args/make-python-environment/default.nix
src/args/make-script/default.nix
src/args/make-template/default.nix
src/evaluator.nix
src/modules/default.nix
src/modules/inputs.nix
src/modules/outputs/builtins/format-bash/default.nix
src/modules/outputs/builtins/format-nix/default.nix
src/modules/outputs/builtins/format-python/default.nix
src/modules/outputs/builtins/lint-bash/default.nix
src/modules/outputs/builtins/lint-commit-msg/default.nix
src/modules/outputs/builtins/lint-markdown/default.nix
src/modules/outputs/builtins/lint-nix/default.nix
src/modules/outputs/builtins/lint-python/default.nix
src/modules/outputs/default.nix

- Standardize the arguments that are propagated to functions,
so code is more readable

refac(build): #171 cleaner arguments

---

src/modules/outputs/builtins/default.nix

- Now builtins are discovered automatically

refac(build): #181 automatic discovery

---

README.md

- Document how you can pin nixpkgs

feat(doc): #171 document how to pin inputs

---

src/cli/main/__main__.py
src/modules/outputs/builtins/lint-commit-msg/default.nix
src/modules/outputs/builtins/lint-markdown/default.nix
src/modules/required-makes-version.nix

- By forcing the path to be dumped into the store
we will work over the NAR serialization of the path
which is a hash

feat(build): #171 reproducibility

---

README.md
makes/main.nix
src/args/deploy-container-image/default.nix
src/args/make-node-environment/default.nix
src/args/make-parallel/default.nix
src/args/make-python-environment/default.nix
src/args/make-script/default.nix
src/args/make-search-paths/default.nix
src/evaluator/modules/outputs/builtins/format-bash/default.nix
src/evaluator/modules/outputs/builtins/format-markdown/default.nix
src/evaluator/modules/outputs/builtins/format-nix/default.nix
src/evaluator/modules/outputs/builtins/format-python/default.nix
src/evaluator/modules/outputs/builtins/lint-bash/default.nix
src/evaluator/modules/outputs/builtins/lint-commit-msg/default.nix
src/evaluator/modules/outputs/builtins/lint-markdown/default.nix
src/evaluator/modules/outputs/builtins/lint-nix/default.nix
src/evaluator/modules/outputs/builtins/lint-python/default.nix

- Make simpler to understand the arguments of
makeSearchPaths
- Classified them by lang

refac(build): #173 make search paths

---

README.md

- Continue writing docs on how to extend Makes

feat(doc): #36 document how to extend makes

---

README.md

feat(doc): #36 provider comparison

---

README.md

- Document inputs of makeSearchPaths

feat(doc): #36 document make search paths

---

README.md
src/args/make-search-paths/default.nix

- This is the real name for what we are trying to
express

refac(cross): #36 rename ldlib to rpath

---

README.md
src/args/make-script/default.nix
src/args/make-search-paths/default.nix
src/args/make-template/default.nix

- Add initial docs for makeDerivation

feat(doc): #36 document make derivation

---

makes/main.nix
src/args/deploy-container-image/default.nix
src/args/deploy-container-image/entrypoint.sh
src/args/make-derivation/default.nix
src/args/make-parallel/default.nix
src/args/make-parallel/entrypoint.sh
src/args/make-script/default.nix
src/args/make-script/template.sh
src/args/make-template/builder.sh
src/args/make-template/default.nix
src/evaluator/modules/outputs/builtins/format-bash/default.nix
src/evaluator/modules/outputs/builtins/format-bash/entrypoint.sh
src/evaluator/modules/outputs/builtins/format-markdown/default.nix
src/evaluator/modules/outputs/builtins/format-markdown/entrypoint.sh
src/evaluator/modules/outputs/builtins/format-nix/default.nix
src/evaluator/modules/outputs/builtins/format-nix/entrypoint.sh
src/evaluator/modules/outputs/builtins/format-python/default.nix
src/evaluator/modules/outputs/builtins/format-python/entrypoint.sh
src/evaluator/modules/outputs/builtins/lint-commit-msg/default.nix
src/evaluator/modules/outputs/builtins/lint-commit-msg/entrypoint.sh

- Now the API is very intuitive, it says replace,
and it replaces the args with the value

refac(build): #173 redesign make-template and make-script

---

README.md
src/args/make-script/default.nix
src/args/make-script/template.sh
src/args/make-search-paths/default.nix

- Add documentation for make-script

feat(cross): #36 document make-script

---

.github/workflows/dev.yml
.github/workflows/prod.yml
.github/workflows/release.yml
README.md
default.nix
makes.nix
makes/main.nix
src/cli/main/__main__.py

- Use first positional argument for passing src
- Always require a src
- Release new makes version as this is a breaking change

feat(back): #188 deprecate m_from

---

README.md

- Small adaptations to documentation

feat(doc): #188 adapt doc

---

README.md
justfile
src/args/make-derivation/default.nix
src/args/make-script/builder.sh
src/args/make-script/template.sh
src/args/make-search-paths/default.nix
src/args/make-template/builder.sh
src/args/make-template/default.nix
src/cli/main/__main__.py

- Add support for github and gitlab repos
and commits, tags, or branches
- Remove M_DEBUG env var, debug by default
- When building templates, cat them
- Adjust docs

feat(cross): #188 support github and gitlab

---

src/cli/main/__main__.py

fix(back): #188 gitlab url

---

README.md

feat(doc): #36 document path

---

README.md

- Extend path explantation
- Remove unused arg in example

feat(doc): #36 extend path

---

src/cli/main/__main__.py

perf(back): #214 rm dirs on exit

---

.github/workflows/release.yml
README.md
default.nix
makes.nix
makes/main.nix
src/cli/main/__main__.py

- It is july, so we are developing august version

refac(cross): #216 downgrade to 21.08

---

README.md
src/args/make-search-paths/default.nix
src/cli/main/__main__.py

- Add support for mypy 37 and 39

feat(build): #188 support mypy 37 and 39

---

src/args/default.nix
src/evaluator/modules/outputs/builtins/__all__/default.nix
src/evaluator/modules/outputs/default.nix

- Reuse this function as i will need it for the third
time

feat(build): #135 abstract function

---

makes.nix
src/evaluator/modules/caches.nix
src/evaluator/modules/default.nix

- Add a moduel for the caching system with cachix

feat(build): #135 caches module

---

makes.nix
src/cli/main/__main__.py
src/evaluator/modules/caches.nix

- Adjust the CLI so we read caches
- Pending to push

feat(build): #135 read caches

---

makes.nix
makes/main.nix
src/cli/main/__main__.py
src/evaluator/modules/caches.nix

- Adjust the CLI and module so we write to caches

feat(build): #135 write to caches

---

README.md

- Add section as other sections do

refac(doc): #135 add section

---

.github/workflows/prod.yml
README.md
makes.nix

- Try to use ephemeral secrets, remove gitlab support
so we can remove gitlab secrets

refac(build): #135 minimal exposure

---

src/cli/main/__main__.py

- If the var is set it logins automatically

refac(back): #135 no need to auth

---

default.nix
src/args/default.nix
src/evaluator/default.nix
src/evaluator/modules/default.nix
src/evaluator/modules/outputs/builtins/default.nix
src/evaluator/modules/outputs/default.nix

- This makes Nix evaluation faster and makes cache
stronger

refac(build): #232 load files instead of folders

---

src/args/format-terraform/default.nix
src/args/format-terraform/entrypoint.sh

- Add an argument for formatting terraform

feat(build): #232 format terraform arg

---

.github/workflows/dev.yml
README.md
makes.nix
src/evaluator/modules/outputs/builtins/default.nix
src/evaluator/modules/outputs/builtins/format-terraform/default.nix

- Add a module for formatting terraform

feat(build): #232 format terraform module

---

.github/workflows/dev.yml
README.md
makes.nix
src/evaluator/modules/outputs/builtins/default.nix
src/evaluator/modules/outputs/builtins/lint-with-lizard/builder.sh
src/evaluator/modules/outputs/builtins/lint-with-lizard/default.nix

- Support lizard CCN and length flags

feat(build): #234 support lizard

---

README.md

- Change from direct links to markdown references

refac(doc): #234 use markdown references

---

.github/workflows/release.yml
README.md
src/evaluator/modules/outputs/builtins/lint-with-lizard/builder.sh

- Use the ephemeral token, the env var no longer exist

fix(build): #232 ephemeral token

---

src/evaluator/modules/outputs/builtins/lint-python/default.nix

- Load only directories from the dirOfModules

feat(build): #29 load only directories

---

LICENSE

- The most permissive out there, OSI approved

refac(conf): #0 from mit license to unlicense

---

README.md

refac(doc): #232 examples

---

README.md

feat(doc): #36 document as bash array

---

README.md
makes.nix
src/args/default.nix
src/args/to-module-outputs/default.nix
src/evaluator/modules/outputs/builtins/lint-python/default.nix
src/evaluator/modules/outputs/builtins/lint-terraform/default.nix

- Some modules produce many outputs, lets
create a function that abstracts the heavy lifting

refac(build): #232 standardize multi outputs

---

README.md

- Use DevSecOps to refer to the term

refac(doc): #232 decsecops

---

README.md
src/args/make-secret-for-aws-from-env/template.sh
src/evaluator/modules/secrets.nix

- Default values must be env vars

fix(build): #252 default values

---

.github/workflows/dev.yml
.mailmap
README.md
makes.nix
src/args/default.nix
src/args/lint-git-mailmap/default.nix
src/args/lint-git-mailmap/entrypoint.sh
src/evaluator/modules/outputs/builtins/default.nix
src/evaluator/modules/outputs/builtins/lint-git-mailmap/default.nix

- Add lintGitMailMap, docs, module, arg, etc

feat(build): #262 lint git mailmap

---

README.md

- Add contact and contributing sections

feat(doc): #262 contact and contrubuting

---

README.md

feat(doc): #262 improve contributing

---

.github/workflows/dev.yml
README.md
makes.nix
src/args/default.nix
src/args/test-terraform/default.nix
src/args/test-terraform/entrypoint.sh
src/evaluator/modules/outputs/builtins/default.nix
src/evaluator/modules/outputs/builtins/test-terraform/default.nix

- Add /testTerraform to makes.nix
- Add argument, docs, etc

feat(build): #232 test terraform

---

.github/workflows/dev.yml
README.md
makes.nix
src/args/default.nix
src/args/deploy-terraform/default.nix
src/args/deploy-terraform/entrypoint.sh
src/evaluator/modules/outputs/builtins/default.nix
src/evaluator/modules/outputs/builtins/deploy-terraform/default.nix

- Add /deployTerraform to makes.nix
- Add arguments, docs, etc

feat(build): #232 deploy terraform

---

README.md

- I will share the project on Nix weekly,
so I gave it another read and adjusted
some descriptions

feat(build): #232 prepare docs

---

src/cli/main/__main__.py

- Tell more information in the CLI

feat(front): #232 tell more info in cli

---

README.md

- Organize sections
- Explain makes.nix format

feat(doc): #232 organize sections

---

.mailmap
src/args/default.nix
src/args/lint-with-lizard/builder.sh
src/args/lint-with-lizard/default.nix

feat(build): #234 target for lint with lizard

---

.github/workflows/dev.yml
README.md
makes.nix
src/args/lint-with-lizard/builder.sh
src/args/lint-with-lizard/default.nix
src/evaluator/modules/outputs/builtins/lint-with-lizard/default.nix

- Since we will be linting autonomic by language
then lets allow having lint groups so they
can group by language

refac(build): #234 target groups

---

src/args/as-bash-map/default.nix
src/args/as-bash-map/template.sh
src/args/default.nix

- Ease the way of creating associative arrays

feat(build): #279 as bash map

---

src/args/as-bash-array/default.nix
src/args/default.nix
src/args/format-bash/entrypoint.sh
src/args/format-terraform/entrypoint.sh
src/args/lint-with-lizard/builder.sh
src/args/make-script-parallel/entrypoint.sh
src/args/make-script/builder.sh
src/evaluator/modules/outputs/builtins/format-markdown/entrypoint.sh
src/evaluator/modules/outputs/builtins/format-nix/entrypoint.sh
src/evaluator/modules/outputs/builtins/format-python/entrypoint.sh
src/evaluator/modules/outputs/builtins/lint-bash/builder.sh
src/evaluator/modules/outputs/builtins/lint-markdown/builder.sh
src/evaluator/modules/outputs/builtins/lint-nix/builder.sh

- Make function return a nix store path with
a local definition of the array
- Adapt all args and modules that use it

feat(back): #277 redesign as bash array

---

README.md
src/args/as-bash-array/default.nix

- Update documentation for simplified use

feat(doc): #277 update as bash array

---

README.md

- Add some minor corrections to examples

fix(doc): #277 minor corrections

---

src/args/default.nix
src/args/paths-matching/default.nix

feat(build): #234 add path matching

---

src/args/paths-matching/default.nix

- Change prefix in pathsMatching args

refac(build): #243 change prefix

---

.github/workflows/dev.yml
makes.nix
src/args/default.nix
src/args/make-secret-for-terraform-from-env/default.nix
src/args/make-secret-for-terraform-from-env/template.sh
src/evaluator/modules/secrets.nix

- Add a module and args for managing terraform
secrets (TF_VAR_xxx=yyy) in a secure and declarative
way

feat(build): #252 terraform secrets

---

src/evaluator/modules/default.nix
src/evaluator/modules/secrets-for-aws-from-env.nix
src/evaluator/modules/secrets-for-terraform-from-env.nix

- Split in two files as they are now two
different modules in the config

refac(build): #252 split terraform secrets

---

.github/workflows/dev.yml
README.md
makes.nix
src/args/make-env-vars-for-terraform/default.nix
src/args/make-env-vars-for-terraform/template.sh
src/evaluator/modules/env-vars-for-terraform.nix

- Add args and module for propagating
env vars to terraform, they should not be
secrets and I will document that later

feat(build): #252 env vars for terraform

---

README.md
makes.nix
src/args/default.nix
src/args/make-env-vars/default.nix
src/args/make-env-vars/template.sh
src/evaluator/modules/default.nix
src/evaluator/modules/env-vars-for-terraform.nix
src/evaluator/modules/env-vars.nix

- Add args and module for propagating env vars
to Bash, they should not be secrets and I will
document that later

feat(build): #252 env vars

---

README.md
makes.nix
src/args/deploy-terraform/default.nix
src/args/lint-terraform/default.nix
src/args/test-terraform/default.nix
src/evaluator/modules/outputs/builtins/deploy-terraform/default.nix
src/evaluator/modules/outputs/builtins/lint-terraform/default.nix
src/evaluator/modules/outputs/builtins/test-terraform/default.nix

- From authentication to setup, as it now reflects
more closely what we are doing

refac(build): #252 rename authentication

---

src/args/make-env-vars-for-terraform/default.nix
src/args/make-env-vars-for-terraform/template.sh
src/args/make-env-vars/default.nix
src/args/make-env-vars/template.sh
src/args/make-secret-for-aws-from-env/default.nix
src/args/make-secret-for-aws-from-env/template.sh
src/args/make-secret-for-terraform-from-env/default.nix
src/args/make-secret-for-terraform-from-env/template.sh

- Display what are we doing with secrets, it looks
just awesome
- I am uploading a showcase next so people get to
know what makes is about in a page

feat(front): #252 display more info

---

makes/main.nix
src/args/default.nix
src/args/path-dirs/default.nix
src/cli/main/__main__.py
src/evaluator/default.nix
src/evaluator/modules/outputs/builtins/deploy-terraform/default.nix
src/evaluator/modules/outputs/builtins/lint-python/default.nix
src/evaluator/modules/outputs/builtins/lint-terraform/default.nix
src/evaluator/modules/outputs/builtins/lint-with-lizard/default.nix
src/evaluator/modules/outputs/builtins/test-terraform/default.nix
src/evaluator/modules/outputs/extended/default.nix

- Manage strings context so we dont introduce
accidental dependencies that cache cache misses
- Use the new pathCopy function where possible

perf(build): #292 optimize path loads

---

src/args/default.nix
src/args/make-secret-for-aws-from-env/template.sh
src/args/make-secret-for-env-from-sops/default.nix
src/args/make-secret-for-env-from-sops/template.sh
src/args/path-copy/default.nix
src/evaluator/modules/default.nix
src/evaluator/modules/secrets-for-env-from-sops.nix

feat(build): 252 sops secrets

---

.github/workflows/dev.yml
README.md
makes.nix
src/args/default.nix
src/args/secure-python-with-bandit/builder.sh
src/args/secure-python-with-bandit/default.nix
src/cli/main/__main__.py
src/evaluator/modules/outputs/builtins/default.nix
src/evaluator/modules/outputs/builtins/secure-python-with-bandit/default.nix

- Add args, module, job, etc for running bandit over
python

feat(build): #298 secure python with bandit

---

src/args/lint-git-mailmap/default.nix

- Propagate nixpkgs from makes for purity

feat(build): #0 use nixpkgs from makes

---

src/args/lint-with-lizard/builder.sh
src/args/lint-with-lizard/default.nix

- Now, each item in the list of the output executed will have an
independent derivation

feat(build): #300 build at the solution level

---

src/args/as-bash-array/default.nix
src/args/default.nix
src/args/lint-with-ajv/builder.sh
src/args/lint-with-ajv/default.nix
src/evaluator/modules/outputs/builtins/default.nix
src/evaluator/modules/outputs/builtins/lint-with-ajv/default.nix

- Add base arg and output
- Supporting multiple schemas still pending

[WIP] feat(build): #303 base arg and output

---

README.md

feat(doc): #303 lint-with-ajv

---

.github/workflows/dev.yml
README.md

feat(cross): #310 update lintm markdown

---

src/args/make-derivation-parallel/default.nix
src/args/make-derivation/default.nix
src/args/to-file-json/default.nix

- Use JSON to dump the list to a file

feat(build): #313 allow longer lists

---

README.md

- Document the new versioning scheme

feat(doc): #313 document new versioning scheme

---

src/args/paths-matching/default.nix

- Allow multiple targets in pathMatching function

refac(build): #317 allow miltiple targets

---

.github/workflows/dev.yml
src/cli/main/__main__.py

feat(build): #319 add macos pipeline

---

src/evaluator/default.nix

- Pin everything in the evaluator, for maximum
reproducibility

feat(build): #0 allow pining everything

---

.github/workflows/dev.yml
README.md
makes.nix
src/args/default.nix
src/args/lint-clojure/builder.sh
src/args/lint-clojure/default.nix
src/evaluator/modules/outputs/builtins/default.nix
src/evaluator/modules/outputs/builtins/lint-clojure/default.nix

- Add support to lint clojure code using clj-kondo

refac(build): #320 support clojure linter

---

src/args/as-bash-array/default.nix
src/args/as-bash-map/default.nix
src/args/default.nix
src/args/make-derivation/default.nix
src/args/project-path-ls-dirs/default.nix
src/args/project-paths-matching/default.nix
src/args/to-module-outputs/default.nix

- Include some lib functions as arguments

refac(build): #0 include lib functions

---

README.md
src/args/as-bash-array/default.nix
src/args/as-bash-array/template.sh
src/args/as-bash-map/default.nix
src/args/format-bash/entrypoint.sh
src/args/format-terraform/entrypoint.sh
src/args/lint-markdown/builder.sh
src/args/lint-with-ajv/builder.sh
src/args/make-script-parallel/entrypoint.sh
src/args/make-script/builder.sh
src/args/make-secret-for-env-from-sops/template.sh
src/evaluator/modules/outputs/builtins/format-markdown/entrypoint.sh
src/evaluator/modules/outputs/builtins/format-nix/entrypoint.sh
src/evaluator/modules/outputs/builtins/format-python/entrypoint.sh
src/evaluator/modules/outputs/builtins/lint-bash/builder.sh
src/evaluator/modules/outputs/builtins/lint-nix/builder.sh

- builtins.toFile cannot refer to derivation outputs
- Lets use makeTemplate to enhance this behaviour

feat(build): #0 as bash array references

---

src/args/make-derivation/default.nix
src/args/make-script/default.nix

- Allow special elements in the name of makeScript
outputs

fix(build): #0 special elements in names

---

src/args/make-derivation/default.nix
src/args/make-script/default.nix
src/args/make-template/default.nix
src/cli/main/__main__.py

- Handling actions as bash scripts eases a lot the
actions handling

refac(cross): #0 actions as bash script

---

makes.nix
src/args/make-derivation/default.nix
src/args/make-template/builder.sh
src/evaluator/modules/default.nix
src/evaluator/modules/pipelines/default.nix
src/evaluator/modules/pipelines/entrypoint-for-job.sh
src/evaluator/modules/pipelines/entrypoint-for-pipeline.sh

- Add basic pipeline support for makes
- Pending to implement needs and auto-generate
the .gitlab-ci.yaml / github actions out of it

feat(build): #180 basic pipeline support

---

README.md

- Add some learning resources to answer a question
made to me

feat(doc): #0 learning resources

---

README.md
src/args/default.nix
src/args/from-yaml/default.nix
src/args/to-file-json-from-file-yaml/builder.sh
src/args/to-file-json-from-file-yaml/default.nix

feat(back): #344 yaml-to-json

---

README.md

- Add doc for toFileJsonFromFileYaml
- Add doc for fromYaml

[WIP] feat(doc): #344 document yaml

---

src/args/make-template/builder.sh

- Use positional arguments in rpl

fix(back): #347 use pos args

---

src/args/from-yaml/default.nix
src/cli/main/__main__.py

- Remove unexisting paths from ephemeral HEAD
if they were removed in staging

fix(back): #349 rm unexisting paths

---

README.md
src/args/make-search-paths/default.nix

- Add environment variable for pkg-config

feat(build): #351 add environment variable

---

.github/workflows/prod.yml

- Remove needs from prod workflow

fix(build): remove needs

---

.github/workflows/prod.yml
justfile

- Propagate secrets to the workflow

refac(build): #0 propagate secrets

---

README.md

feat(doc): #36 document env-vars

---

README.md

- Document envVarsForTerraform

feat(doc): #36 document env-vars-for-terraform

---

README.md

- Improve types description so self references are
more clear

feat(doc): #36 improve types desc

---

README.md

- Add some badges and remove scalability from
github

feat(doc): #36 add badges

---

README.md

- Standardize types section
- Fix some examples syntax

feat(doc): #36 standardize types

---

README.md

feat(doc): #36 make container image

---

README.md

- So they load faster and anchors do not break

refac(doc): #36 smaller images

---

README.md
src/args/make-node-interpreter/default.nix
src/args/make-node-modules/default.nix

[WIP] feat(doc): #361 document node

---

README.md

- Add documentation for makePythonEnvironment

feat(doc): #36 document python env

---

src/args/calculate-cvss-3/builder.sh
src/args/calculate-cvss-3/cvss.py
src/args/calculate-cvss-3/default.nix
src/args/default.nix

- Add arg for returning json cvss3 for a vector string

feat(back): #375 add arg

---

README.md

- Add documentation for calculateCvss3

feat(doc): #375 calculate cvss

---

src/args/calculate-cvss-3/default.nix

- Use direct path to file
as arg can't find the file in other repos

fix(back): #375 path to file

---

src/args/calculate-cvss-3/default.nix

- Remove unnecessary arg to fix linter

fix(build): #375 rm unnecessary arg

---

src/cli/main/__main__.py

- Allow commits in remote projects

feat(build): #380 allow commits in remote

---

src/cli/main/__main__.py

perf(build): #374 push runtime deps

---

README.md
src/args/make-secret-for-env-from-sops/default.nix
src/args/make-secret-for-env-from-sops/template.sh
src/evaluator/modules/secrets-for-env-from-sops/default.nix

- Document the secrets backend

feat(doc): #36 document more secrets

---

README.md
makes.nix
src/args/fetch-nixpkgs/default.nix

- Document fetchNixpkgs
- Simplify its signature, a sha256 is not required
for git repositories

feat(doc): #36 document fetch nixpkgs

---

README.md
makes.nix
src/args/default.nix
src/args/fetch-github/default.nix
src/args/fetch-nixpkgs/default.nix
src/args/lint-git-mailmap/default.nix

- seems like fetchgit is not well supported by Nix

refac(cross): #36 sha256 again

---

README.md

feat(doc): #36 fetch url

---

README.md
src/args/to-bash-map/default.nix

feat(doc): #36 to bash map

---

.github/workflows/prod.yml
README.md
makes.nix
makes/main.nix
src/cli/main/__main__.py

refac(cross): #0 september release

---

justfile
src/args/default.nix
src/args/to-file-yaml/default.nix

- Add a helper toFileYaml to dump the gitlab-ci
from Makes

feat(back): #36 add to file yaml

---

README.md

feat(doc): #36 document to file json

---

README.md

feat(doc): #36 document to file yaml

---

src/args/default.nix
src/args/make-derivation/default.nix
src/args/to-bash-map/default.nix
src/args/to-module-outputs/default.nix
src/evaluator/modules/cache/default.nix
src/evaluator/modules/default.nix

- Standardize functions to handle attrsets

refac(build): #180 standardize attr func

---

makes.nix
src/evaluator/modules/pipelines/default.nix
src/evaluator/modules/pipelines/entrypoint-for-pipeline-on-gitlab.sh

- Add gitlab metadata so we can generate the
gitlab-ci.yaml

feat(build): #180 gitlab metadata

---

src/evaluator/modules/pipelines/default.nix

- Add script on gitlab ci.yaml

feat(build): #180 add script

---

src/args/gitlab-ci/default.nix
src/evaluator/modules/pipelines/default.nix

- Add more gitlab abstractions

feat(build): #180 gitlab abstractions

---

src/evaluator/modules/pipelines/default.nix
src/evaluator/modules/pipelines/entrypoint-for-pipeline-on-gitlab.sh

- Fail on differences, so one can use this
job to validate the gitlab-ci

feat(build): #180 fail on diff

---

README.md
src/args/make-search-paths/default.nix

- Add support for KUBECONFIG env var

feat(build): #404 kubernetes config

---

src/args/default.nix
src/args/make-secret-for-kubernetes-config-from-aws/default.nix
src/args/make-secret-for-kubernetes-config-from-aws/template.sh

- Add argument for this component

feat(build): #404 kube config secret

---

README.md
src/args/test-terraform/default.nix
src/args/test-terraform/entrypoint.sh
src/evaluator/modules/test-terraform/default.nix

- Support debugging in testTerraform

feat(build): #408 terraform debug

---

src/args/default.nix
src/args/taint-terraform/default.nix
src/args/taint-terraform/entrypoint.sh

- Add a terraform taint argument

feat(build): #410 terraform taint

---

.github/workflows/prod.yml

- Fix deployment command by installing from source

fix(build): #0 deployment

---

.github/workflows/dev.yml
README.md
makes.nix
src/args/taint-terraform/entrypoint.sh
src/evaluator/modules/default.nix
src/evaluator/modules/taint-terraform/default.nix
test/terraform/module/main.tf

- Add a taint terraform module

feat(build): #410 taint terraform module

---

src/evaluator/modules/lint-nix/builder.sh

- Add more possible options
- Refactor code

refac(build): #415 possible options

---

src/args/gitlab-ci/default.nix

- Add more gitlab rules abstractions

feat(build): #0 more gitlab abstractions

---

src/args/taint-terraform/default.nix
src/args/taint-terraform/entrypoint.sh
src/evaluator/modules/taint-terraform/default.nix

- Allow redeploying infrastructure after tainting
resources

feat(build): #0 allow redeploying infra

---

README.md
src/args/gitlab-ci/default.nix

- After it failed and reading the docs, we should
compare to null

fix(build): #0 gitlab defined var

---

README.md
src/args/deploy-terraform/entrypoint.sh
src/args/format-terraform/default.nix
src/args/lint-terraform/entrypoint.sh
src/args/taint-terraform/entrypoint.sh
src/args/test-terraform/entrypoint.sh
src/evaluator/modules/deploy-terraform/default.nix
src/evaluator/modules/format-terraform/default.nix
src/evaluator/modules/lint-terraform/default.nix
src/evaluator/modules/taint-terraform/default.nix
src/evaluator/modules/test-terraform/default.nix

- Work directly over mutable paths in the repository
so one can get a copy of the state and manage
terraform locks more comfortable

feat(build): #0 mutable terraform

---

src/args/calculate-cvss-3/cvss.py

- Round score to a single decimal digit

refac(back): #375 round scores

---

README.md
makes.nix
src/args/make-terraform-environment/default.nix

- Drop 0.12 and 0.13
- Update jobs

refac(cross): #426 drop terraform versions

---

README.md
src/args/default.nix
src/args/make-python-version/default.nix

- Lets split this python module into submodules

refac(build): #0 make python version

---

README.md
src/args/calculate-cvss-3/default.nix
src/args/lint-with-lizard/default.nix
src/args/make-python-environment/default.nix
src/evaluator/modules/lint-python/default.nix

- Reuse python interpreter from the makePythonVersion

refac(build): #0 reuse make python version

---

src/args/default.nix
src/args/to-file-toml/default.nix

- Addd two utils to manipulate TOML within Nix

feat(build): #0 add toml conversion

---

src/nix/sources.json

- Update nixpkgs so we can use modifications
I made there

feat(build): #434 update nixpkgs

---

README.md

feat(doc): #0 document from toml

---

README.md
src/args/make-python-pypi-mirror/builder.sh
src/args/make-python-pypi-mirror/check-completeness.py
src/args/make-python-pypi-mirror/default.nix

- Mirror pypi by copying artifacts for the specific
version
- Use poetry for resolving sub-dependencies and a small
script for the checking dependency completeness

feat(build): #434 mirror pypi

---

src/args/calculate-cvss-3/default.nix
src/args/make-python-pypi-environment/builder.sh
src/args/make-python-pypi-mirror/default.nix

- Create a pypi environment function to create a
virtual environment where the specified pypi
dependencies are present
- Migrate calculateCvss3 to this new function
protected by a hash

feat(build): #434 pypi environment

---

src/args/lint-with-lizard/default.nix
src/args/make-python-pypi-mirror/check-completeness.py

- Make lint with lizard use hashes

refac(build): #434 lint with lizard

---

src/args/make-python-pypi-mirror/builder.sh
src/args/make-python-pypi-mirror/check-completeness.py
src/args/make-python-pypi-mirror/default.nix

- Check versions completeness before downloading

perf(build): #434 check versions faster

---

src/args/make-python-pypi-environment/default.nix
src/args/make-python-pypi-mirror/builder.sh
src/args/make-python-pypi-mirror/check-completeness.py

- Handle tar.gz and whl sources separately as they
are different convention

refac(build): #434 handle different srcs

---

src/args/make-python-pypi-mirror/builder.sh
src/args/make-python-pypi-mirror/default.nix

- Wheel and setuptools are required to be boostraped
- I have found a more elegant way than this but
anyway I am flushing local code to avoid
inventory

refac(build): #434 bootstrap pkgs

---

src/args/lint-with-lizard/default.nix
src/args/make-python-pypi-environment/default.nix
src/evaluator/modules/lint-python/default.nix
src/evaluator/modules/lint-python/settings-mypy.cfg

- Build dependencies for linting python with
the pure builder

refac(build): #434 lint python hash

---

README.md
src/args/agnostic.nix
src/args/default.nix
src/args/format-bash/default.nix
src/args/lint-clojure/default.nix
src/evaluator/modules/format-bash/default.nix

- Make makes agnostic functions be importable outside
of Makes

refac(build): #450 makes agnostic

---

README.md
makes/tests/calculateCvss3/main.nix
src/args/calculate-cvss-3/default.nix

fix(build): #451 calculate cvss 3

---

.github/workflows/dev.yml

- Add test job for the regression test

test(build): #451 add test job

---

README.md

fix(doc): #434 absolute paths

---

makes/utils/makePythonPypiEnvironmentSources/entrypoint.sh
makes/utils/makePythonPypiEnvironmentSources/main.nix

feat(build): #434 handle all formats

---

README.md
src/args/make-python-pypi-environment/builder.sh
src/args/make-python-pypi-environment/default.nix

feat(build): #434 support cython

---

src/args/agnostic.nix
src/args/default.nix
src/args/make-derivation/default.nix
src/evaluator/default.nix
src/nix/packages.nix

- Make the framework compatible with Nix 3 by
not using builtins.currentSystem (which is
not available there

refac(build): #0 system agnostic

---

makes/utils/makePythonPypiEnvironmentSources/entrypoint.sh

- Ignore .eggs, .exes because they are windows-only
or deprecated
- Ignore python implementations not related to the
version we are building agaisnt

perf(build): #434 ignore implementations

---

makes/utils/makePythonPypiEnvironmentSources/entrypoint.sh

refac(build): #434 exclude windows

---

src/args/make-secret-for-env-from-sops/template.sh
src/args/shell-options/template.sh

- Completely disable shopt xpg_echo

fix(back): #464 disable xpg echo

---

src/args/make-python-pypi-environment/default.nix
src/args/make-search-paths/default.nix

- Propagate bootstraped dependencies so they are available
in the final environment
- Refactor make search paths to produce less verbose
sources

feat(build): #434 propagate boostrapped

---

makes/utils/makePythonPypiEnvironmentSources/entrypoint.sh
src/args/calculate-cvss-3/sources.yaml
src/args/lint-with-lizard/sources.yaml
src/args/make-python-pypi-environment/sources/numpy-1.21.2/sources-37.yaml
src/args/make-python-pypi-environment/sources/numpy-1.21.2/sources-38.yaml
src/args/make-python-pypi-environment/sources/numpy-1.21.2/sources-39.yaml
src/evaluator/modules/lint-python/sources-3.7.yaml
src/evaluator/modules/lint-python/sources-3.8.yaml
src/evaluator/modules/lint-python/sources-3.9.yaml

- Discard correctly python implementations other than
the one we are building against

perf(build): #434 discard implementations

---

makes/utils/makePythonPypiEnvironmentSources/entrypoint.sh
src/args/make-python-pypi-environment/sources/numpy-1.21.2/sources-37.yaml

- Exclude PyPy platform, it is incompatible
with CPython

perf(build): #434 exclude pp

---

src/args/make-python-pypi-environment/builder.sh

- Uninstall pip after build step for purity,
it is just a build requirement

refac(build): #434 uninstall pip

---

makes/utils/makePythonPypiEnvironmentSources/update.sh

- Add a script to update all packages from makes

feat(build): #434 add update all script

---

default.nix
makes/main.nix
src/args/default.nix
src/cli/main/__main__.py
src/evaluator/default.nix

- Add an argument that changes on each makes execution

feat(build): #0 makes execution id

---

README.md
makes/utils/makePythonPypiEnvironmentSources/entrypoint.sh
makes/utils/makePythonPypiEnvironmentSources/main.nix
src/args/make-python-pypi-environment/default.nix
src/args/make-python-version/default.nix
src/args/make-search-paths/default.nix

feat(build): #0 support py 36

---

README.md
src/args/lint-python-imports/default.nix
src/evaluator/modules/lint-python/default.nix

- Allow propagating extra sources

feat(build): #0 lint python imports sources

---

.github/workflows/prod.yml
README.md
default.nix
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

refac(cross): #0 bump 21.10

---

src/args/lint-git-commit-msg/commitlint/package-lock.json
src/args/lint-git-commit-msg/commitlint/package.json
src/args/lint-with-ajv/ajv-cli/package-lock.json
src/args/lint-with-ajv/ajv-cli/package.json
src/evaluator/modules/format-markdown/doctoc/package-lock.json
src/evaluator/modules/format-markdown/doctoc/package.json

- Add package-lock.json for packages we use

refac(build): #494 add lock files

---

src/args/make-node-js-npm-environment/builder.sh
src/args/make-node-js-npm-environment/default.nix

- Make this compatible with later versions of node

feat(build): #494 node 16 compat

---

README.md

- Document changes to the NPM packaging functions

feat(build): #494 document new modules

---

src/args/lint-git-commit-msg/default.nix
src/args/lint-with-ajv/default.nix
src/args/make-node-js-environment/default.nix
src/args/make-node-js-modules/builder.sh
src/args/make-node-js-modules/default.nix
src/evaluator/modules/format-markdown/default.nix

- Npm do not link binaries unless it fetches the
internet, so lets patch it

feat(build): #494 link binaries

---

makes/tests/lintWithAjv/data.json
makes/tests/lintWithAjv/data.yaml
makes/tests/lintWithAjv/main.nix
makes/tests/lintWithAjv/schema.json

- Add test for lintWithAjv
- It is still broken but the test will simplify
debugging

test(back): #503 test for lint with ajv

---

.github/workflows/dev.yml

- Turn on test jobs for lint-with-ajv

feat(build): #503 turn on jobs

---

.github/workflows/dev.yml
.github/workflows/prod.yml

- Also configure concurrency so we do not waste
machines and api limits without need

refac(build): #494 do not test in prod

---

.github/workflows/dev.yml
README.md
src/args/make-node-js-modules/default.nix
src/evaluator/modules/format-markdown/default.nix
src/evaluator/modules/lint-git-commit-msg/default.nix
src/evaluator/modules/lint-with-ajv/default.nix

- Building node modules our way only works on Linux
currently
- If someone from community with more MacOS
experience want to give us a hand to debug this
permission error when binding an http server to
127.0.0.1 we'll welcome it!

refac(cross): #494 linux specifics

---

README.md

feat(doc): #147 document it

---

src/args/make-node-js-modules/builder.sh
src/args/make-node-js-modules/default.nix

- Use patch she bangs so it can handle more cases,
also it allows for code reuse in future features

feat(build): #449 use patch she bangs

---

src/args/make-node-js-modules/default.nix

- I found this special case with react native on
Fluid Attacks mobile application

refac(build): #449 handle more tarballs

---

src/evaluator/modules/default.nix

- ProjectPath is not lazy. Use a lazy version to check
path existence

fix(build): #526 projectPath lazyness

---

src/args/agnostic.nix
src/args/make-secret-for-gpg-from-env/default.nix
src/args/make-secret-for-gpg-from-env/template.sh

- Add an argument that turns env vars with PGP public
or private keys exported as ascii armors,
into an ephemeral PGP keyring

feat(build): #528 secret for gpg from env

---

README.md

- Document using gpg secrets and sops

feat(doc): #528 add docs

---

default.nix
flake.lock
flake.nix
makes/main.nix

- Expose m as a flake default app

feat(build): #536 m in flake

---

README.md

- Add docs to tell people how to use makes with
nix flakes

feat(doc): #536 document it

---

src/evaluator/modules/lint-git-mailmap/default.nix

this module was unconditionally enabled

fixup: lint-git-mailmap

---

src/cli/main/__main__.py

- Set the initial branch to something that no repo
should already have

refac(build): #0 set initial branch

---

src/evaluator/modules/lint-git-mailmap/default.nix

- Add a missing function argument

fix(build): #0 undefined var

---

src/args/to-file-json-from-file-yaml/default.nix
src/args/to-file-json/default.nix
src/args/to-file-toml/default.nix
src/args/to-file-yaml/default.nix

- Going to the binary cache for 2500 generated JSONs
is a waste of time, better build them locally

perf(build): #0 local fmt conversion

---

README.md
makes.nix
src/cli/main/__main__.py
src/evaluator/from-flake.nix
src/evaluator/modules/cache/default.nix

- Enable using more read caches

feat(build): #545 more read caches

---

src/cli/main/__main__.py
src/evaluator/from-flake.nix

- Expose internals so the CLI can consume them

feat(build): #546 expose internals

---

default.nix
src/cli/main/__main__.py

- Make the CLI compatible with Flakes via
a feature flag

feat(build): #546 flake compat cli

---

flake.nix
src/evaluator/default.nix

- This merges inputs from the flake and make them
available to scripts under the magic makes/ folder
as well as to the modules configuration
Relates to #540

feat(build): #546 propagate inputs

---

default.nix
src/cli/main/__main__.py

- It was missing to set the searchPaths

fix(build): #546 nix store not found

---

README.md

- Document these builtin functions.

feat(doc): #552 document it

---

flake.nix
src/cli/main/__main__.py

- Use the experimental flake support in this repo to help uncover bugs

feat(build): #546 use experimental flake support

---

README.md
makes/example/main.nix
src/args/agnostic.nix
src/args/fetch-rubygem/default.nix

feat(build): #574 add fetch rubygem

---

README.md
makes/example/main.nix
src/args/make-script/default.nix
src/args/make-search-paths/default.nix

- Add a generic purpose export interface for using
complex use cases

feat(build): #588 export interface

---

README.md
src/args/agnostic.nix
src/args/make-ruby-gems-install/builder.sh
src/args/make-ruby-gems-install/default.nix

- Add a function to fetch and install some gems

feat(build): #574 make ruby gem install

---

src/args/make-ruby-gems-install/builder.sh
src/args/make-ruby-gems-install/default.nix

- Patch shenbangs so they point to the nix store

feat(build): #574 patch bin shebangs

---

README.md
src/args/make-search-paths/default.nix

- Define ruby search paths in a consistent way to
our fetchers and builders

feat(build): #574 ruby search paths

---

README.md
src/args/agnostic.nix
src/args/make-ruby-gems-environment/default.nix
src/args/make-ruby-gems-install/builder.sh

- Create a ruby environment where the gems are
available

feat(build): #574 make ruby env

---

src/cli/main/__main__.py

- Add a feature flag for running makes
on an unprivileged kubernetes cluster
- Dont know if this is the solution but it is
my best guess

feat(build): #599 k8s compatibility

---

README.md
src/args/make-ruby-gems-environment/default.nix
src/args/make-ruby-gems-install/default.nix

- Allow passing extra search paths for being able
to compile gems with native extensions
- Also add a runtime flag

feat(build): #574 extra search paths

---

src/args/make-script/template.sh

- Enable to ask user for input

feat(build): #0 add user input prompt

---

src/cli/main/__main__.py

- Cache downloads for one day, but tell users that
they are using a cached version and its location
so if they want to upgrade they can just delete
such location

perf(back): #598 downloads cache

---

flake.nix
src/args/default.nix
src/cli/main/__main__.py
src/evaluator/default.nix
src/evaluator/modules/deploy-terraform/default.nix
src/evaluator/modules/format-bash/default.nix
src/evaluator/modules/format-markdown/default.nix
src/evaluator/modules/format-nix/default.nix
src/evaluator/modules/format-python/default.nix
src/evaluator/modules/format-terraform/default.nix
src/evaluator/modules/lint-git-commit-msg/default.nix
src/evaluator/modules/lint-git-mailmap/default.nix
src/evaluator/modules/lint-terraform/default.nix
src/evaluator/modules/pipelines/default.nix
src/evaluator/modules/taint-terraform/default.nix
src/evaluator/modules/test-terraform/default.nix

refac(build): #567 drop path mutable

---

README.md

- Add more use cases into add a glance

feat(doc): #0 at a glance

---

makes.nix
makes/tests/secureNixWithVulnix/main.nix
src/args/agnostic.nix
src/args/fetch-github/default.nix
src/args/secure-nix-with-vulnix/default.nix
src/args/secure-nix-with-vulnix/entrypoint.sh
src/evaluator/modules/default.nix
src/evaluator/modules/secure-nix-with-vulnix/default.nix

- Add a proof of concept of vulnix

feat(build): #608 vulnix poc

---

README.md
src/evaluator/modules/secure-nix-with-vulnix/default.nix

feat(build): #608 vulnix docs

---

.github/workflows/dev.yml
README.md
src/args/secure-nix-with-vulnix/default.nix
src/evaluator/modules/secure-nix-with-vulnix/default.nix

feat(build): #608 add tests

---

src/args/agnostic.nix
src/args/compute-on-aws-batch/default.nix
src/args/compute-on-aws-batch/entrypoint.sh

- Add an argument that allows sending jobs to
aws batch

feat(build): #614 compute on aws batch

---

src/args/compute-on-aws-batch/default.nix
src/args/compute-on-aws-batch/entrypoint.sh
src/evaluator/modules/compute-on-aws-batch/default.nix
src/evaluator/modules/default.nix

- Add a module to parametrize computing jobs
on batch

feat(build): #614 compute batch module

---

README.md
src/evaluator/modules/compute-on-aws-batch/default.nix

feat(doc): #614 document module

---

README.md
src/args/compute-on-aws-batch/default.nix
src/args/compute-on-aws-batch/entrypoint.sh
src/evaluator/modules/compute-on-aws-batch/default.nix

- Add a generalization of the problem to avoid
sending duplicates to batch

feat(build): #614 allow duplicates flag

---

README.md
src/args/compute-on-aws-batch/default.nix
src/args/compute-on-aws-batch/entrypoint.sh
src/evaluator/modules/compute-on-aws-batch/default.nix

- Make positional arguments part of the job name

feat(build): #614 nicer names

---

README.md

- Expose aws batch on the main page

feat(build): #614 at a glance

---

README.md
src/args/compute-on-aws-batch/entrypoint.sh
src/evaluator/modules/compute-on-aws-batch/default.nix

- Allow picking the queue at runtime

feat(build): #614 runtime queue

---

src/args/test-python/default.nix
src/evaluator/modules/default.nix
src/evaluator/modules/test-python/default.nix

- Add a module for configuring testPython
declaratively

feat(build): #624 test python module

---

.github/workflows/dev.yml
makes.nix
test/test-python/test_something.py

- Add tests and test jobs for this module

test(build): #624 test python tests

---

src/args/test-python/pypi-sources-3.6.yaml
src/args/test-python/pypi-sources-3.8.yaml
src/args/test-python/pypi-sources-3.9.yaml

- I generated closures for the wront interpreters,
this fixes them

fix(build): #624 python interpreters

---

README.md
src/args/lint-python-imports/default.nix
src/args/lint-python/default.nix
src/args/test-python/default.nix
src/evaluator/modules/lint-python/default.nix
src/evaluator/modules/test-python/default.nix

- Lets use bare searchPaths as this is what other
modules in the framework use

feat(build): #624 standardize setup

---

src/args/test-python/entrypoint.sh

- Propagate extra flags to pytest

feat(build): #624 propagate flags

---

README.md
src/args/agnostic.nix
src/args/lib-git/default.nix
src/args/lib-git/template.sh

- Add a library for git utilities

feat(cross): #632 lib git

---

src/args/test-python/default.nix
src/args/test-python/entrypoint.sh
src/evaluator/modules/test-python/default.nix

- Add a standard mechanism for testing with many sources
side by side

feat(build): #624 extra sources

---

README.md
src/args/make-script/template.sh

- Document a few added functions

feat(build): #590 add missing docs

---

README.md

- Clarify a little the versioning schemes

feat(doc): #0 clarify version schemes

---

README.md
default.nix
src/args/agnostic.nix
src/args/default.nix
src/args/make-script/default.nix
src/evaluator/default.nix
src/evaluator/modules/default.nix

- Simplify state directories by setting
some sensible defaults

refac(cross): #0 simplify state dirs

---

README.md

feat(doc): #624 document it

---

src/args/as-content/default.nix
src/args/make-template/default.nix

- Recognize store paths as strings as paths

fix(build): #644 handle store paths

---

README.md
src/args/lib-git/template.sh

- Add a function to compute a commit sha from
a revision

feat(build): #0 sha from rev

---

default.nix
src/cli/main/__main__.py
src/cli/main/registry.json

- Add a registry of Makes projects so people
can benefit from aliases

feat(build): #188 registry of projects

---

src/comp/bash.sh

- Add a script for bash completion
- It is meant to be sourced in bashrc and
after it it autocompletes sources and
outputs

feat(build): #548 bash completion

---

README.md
default.nix

- Install bash completions together with the main
binary

feat(build): #548 install bash comp

---

README.md
makes.nix
src/args/deploy-container-image/default.nix
src/args/deploy-container-image/entrypoint.sh
src/evaluator/modules/deploy-container-image/default.nix

- Allow picking the number of deployment attempts

feat(build): #655 retry deployment

---

README.md
src/args/make-search-paths/default.nix

- Add (basic) Ocaml search paths
- Even if basic, the use case is covered

feat(build): #650 ocaml search paths

---

README.md
src/args/make-search-paths/default.nix

- Add search paths for crystal

feat(build): #653 search paths crystal

---

README.md
src/args/make-search-paths/default.nix

- Add support for ocaml stublibs path caml_ld_library_path

feat(build): #650 ocaml stublibs paths

---

src/args/lint-git-mailmap/default.nix

- Update mailmap linter so it handle more names correctly

refac(build): #0 update mailmap linter

---

src/args/deploy-container-image/entrypoint.sh

- Handle the exit code correctly, on
subshells it works weirdly

refac(build): #0 correctly handle exit

---

.gitlab-ci.yaml
src/evaluator/modules/pipelines/default.nix

- On Gitlab, use the args as part of the name

refac(build): #0 uniq job names

---

README.md
src/args/agnostic.nix

feat(doc): #0 add more badges

---

src/evaluator/modules/pipelines/default.nix

- Allow people overriding our defined values
with gitlabExtra

refac(build): #0 allow overrides

---

README.md
src/args/lint-python/default.nix
src/args/lint-python/pypi-deps.yaml
src/args/lint-python/pypi-sources-3.7.yaml
src/args/lint-python/pypi-sources-3.8.yaml
src/args/lint-python/pypi-sources-3.9.yaml
src/args/make-python-pypi-environment/default.nix
src/cli/main/__main__.py

- update prospector in all python versions

feat(build): #672 update prospector

---

SECURITY.md

feat(doc): #0 add sec policy

---

.mailmap
src/args/lint-git-commit-msg/commitlint/package.json

- In order to comply with the security advisory

feat(build): #0 update ansi regex

---

src/evaluator/modules/format-markdown/doctoc/package-lock.json

- In order to comply with the security advisory

feat(build): #0 update trim

---

src/args/lint-git-commit-msg/commitlint/package-lock.json
src/args/lint-git-commit-msg/commitlint/package.json

- In order to comply with the security advisories

feat(build): #0 update commitlint

---

.github/workflows/dev.yml
README.md
makes.nix
src/args/make-derivation/default.nix
src/args/make-script/default.nix
src/args/make-search-paths/default.nix
src/args/make-template/default.nix
src/evaluator/modules/default.nix
src/evaluator/modules/dev/default.nix
test/dev/.envrc

- Add the skeleton of a dev module

feat(build): #692 dev module

---

src/args/agnostic.nix
src/args/manage-ports/main.nix
src/args/manage-ports/template.sh

- kill_port
- done_port
- wait_port

manage ports

---

flake.nix
src/args/default.nix
src/cli/main/__main__.py
src/evaluator/default.nix

- No longer needed, can be workaround by other means

refac(build): #564 deprecate exec id

---

src/args/make-dynamodb/default.nix
src/args/make-dynamodb/entrypoint.sh
src/evaluator/modules/dynamodb/default.nix

- add  `dbInfra` parameter, allows adding a path with the infrastructure to create the database tables
- add `dbData` parameter, allows dump database with the previous infra

allow db population

---

src/args/make-dynamodb/default.nix
src/args/make-dynamodb/entrypoint.sh
src/args/manage-ports/template.sh
src/evaluator/modules/dynamodb/default.nix

- sometimes it is required to make transformations to the original data, for this we could use a derivation and its result as a parameter
- allow to execute in daemon mode
- simplify the name of the arguments removed the db prefix

allow data from derivations 

---

README.md
src/args/agnostic.nix
src/args/make-ssl-certificate/builder.sh
src/args/make-ssl-certificate/default.nix

- Create `makeSslCerts` to create self signed SSL certificates

feat(build): #772 create ssl certificates

---

README.md
src/args/make-dynamodb/entrypoint.sh

- overwrite parameters with environment variables
- add doc

feat(back): #683 overwrite parameters

---

makes.nix
test/lint-commit-msg/lint-git-commit-msg-config.js
test/lint-commit-msg/lint-git-commit-msg-parser.js

- Add commit lint config files

feat(build): #769.1 add commit lint config

---

.github/workflows/prod.yml
.gitlab-ci.yaml
.mailmap
README.md
default.nix
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

- 21.12 now becomes the stable version
- 21.13 becomes the unstable release.

refac(cross): #0 bump to 21.13

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
default.nix
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

- 21.12 now becomes the stable version
- 22.01 becomes the unstable release.

refac(cross): #0 bump to 22.01

---

src/args/lint-markdown/builder.sh

- ignore frontmatter from lintMarkdown

refac(cross): #782 ignore frontmatter

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
default.nix
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

- 22.01 now becomes the stable version
- 22.02 becomes the unstable release.

refac(cross): #0 bump to 22.02

---

README.md
src/args/make-node-js-version/default.nix

- Add nodejs-17_x to makeNodeJsVersion

feat(back): #787 support nodejs 17

---

README.md
makes/utils/makeNodeJsLockfile/entrypoint.sh
makes/utils/makeNodeJsLockfile/main.nix

- Script to build `package-lock.json` using makes, to keep lock
versions between the devs involved in a project.

feat(back): #789 build package lock

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
default.nix
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

refac(cross): #0 bump to 22.03

---

.mailmap

fix(doc): #797 fix mailmap

---

.github/workflows/scorecards-analysis.yaml

feat(job): #794 enable scorecard

---

README.md
makes/utils/makeSopsEncryptedFile/entrypoint.sh
makes/utils/makeSopsEncryptedFile/main.nix
makes/utils/makeSopsEncryptedFile/template.yaml

- Add makeSopsEncryptedFile for easily creating
sops encrypted files
- Add documentation for utilities

feat(back): #710 sops encrypted file

---

README.md
makes.nix
src/args/deploy-container-image/default.nix
src/args/deploy-container-image/entrypoint.sh
src/evaluator/modules/deploy-container-image/default.nix

- Add credentials and setup argument to
builtin so all registries can be used

feat(back): #804 all registries

---

README.md
makes.nix
src/args/agnostic.nix
src/args/format-nix-with-alejandra/default.nix
src/args/format-nix-with-alejandra/entrypoint.sh
src/evaluator/modules/default.nix
src/evaluator/modules/format-nix-with-alejandra/default.nix

- Add alejandra basic builtin
- Keep it disabled until we decide
to use it over nix-fmt
- Add doc

feat(back): #806 alejandra builtin

---

README.md
src/args/make-ruby-version/default.nix

- Removed ruby 2.6 from `makeRubyVersion` arg

fix(job): #797 remove ruby 2.6

---

.github/workflows/dev.yml
README.md
makes.nix
src/args/agnostic.nix
src/args/calculate-scorecard/default.nix
src/args/calculate-scorecard/entrypoint.sh
src/evaluator/modules/calculate-scorecard/default.nix
src/evaluator/modules/default.nix

- Create arg `calculateScorecard`
- Create module `calculateScorecard`
- Add documentation for `calculateScorecard` arg and module
- Use scorecard module on makes

feat(cross): #794 calculate scorecard feature

---

.github/workflows/dev.yml
makes/tests/makeTemplate/main.nix
makes/tests/makeTemplate/template.txt

- Add basic test for make template
- Add missing tests to pipeline

test(back): #813 make template test

---

src/args/make-template/builder.sh

- Encode args to replace passed to `makeTemplate` to `UTF-8`

refac(cross): #813 encode args

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
default.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

refac(cross): #0 bump to 22.04

---

.github/workflows/dev.yml
.github/workflows/prod.yml
.github/workflows/scorecards-analysis.yaml
README.md

- Pin dependencies on github workflows
- Specify token permissions on workflows

fix(job): #797 improve score

---

README.md

feat(doc): #822 add new badge

---

README.md

- Use github instead of fluidattacks domain

refac(doc): #827 update install link

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
default.nix
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

- Update makes release to 22.05

refac(back): #0 bump to 22.05

---

src/args/compute-on-aws-batch/default.nix

- Use resource requirements in template

feat(back): #836 use resource requirements

---

.github/workflows/dev.yml
src/cli/main/__main__.py

- Format python cli module
- Update macos nix installation

refac(doc): #797 fix pipeline

---

README.md
src/args/compute-on-aws-batch/default.nix
src/args/compute-on-aws-batch/entrypoint.sh
src/evaluator/modules/compute-on-aws-batch/default.nix

- Support parallel arg on
computeOnAwsBatch so array jobs
can be ran

feat(back): #842 support parallelism

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

refac(cross): #0 makes release

---

README.md
makes/utils/makeNodeJsLockfile/entrypoint.sh
makes/utils/makeNodeJsLockfile/main.nix
src/args/make-node-js-version/default.nix

- Support NodeJs 17 and 18 on `makeNodeJsVersion` and
`makeNodeJsLockfile`
- Update docs

refac(cross): #847 support node 17 18

---

makes.nix

refac(job): #850 update cachix key

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

- makes 22.06 is onw the stable version
- Makes 22.07 is now the unstable version

refac/cross: #0 makes release

---

README.md
flake.lock
makes/utils/makeNodeJsLock/entrypoint.sh
makes/utils/makeNodeJsLock/main.nix
src/args/make-node-js-version/default.nix
src/nix/sources.json

- Update nixpkgs channel
- Remove nodejs-17 support since 18 got released
- Update docs

refac(cross): #858 update nixpkgs

---

src/args/make-node-js-modules/builder.sh

refac(back): #864 fix makenodjsmodules

---

README.md
src/args/make-container-image/default.nix
src/args/make-node-js-modules/builder.sh

- Allow makeContainerImage to specify a maximum
number of layers

feat(back): #866 maxLayers in  makeContainerImage

---

makes/container-image/main.nix

- Decrease makes container layers to 20

refac(infra): #868 decrease layers

---

README.md

- Add new Makes introduction
- Add example section

feat(doc): #511 add example

---

README.md

- Remove blank lines in references

refac(doc): #872 remove blank lines

---

README.md

- As nix profile is still an experimental feature

refac(doc): #874 only support nix-env

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
default.nix
makes.nix
src/cli/main/__main__.py
src/evaluator/modules/pipelines/default.nix

- 22.08 is now the stable version
- 22.09 is now the unstable version

refac(cross): #0 bump to 22.09

---

src/nix/sources.json

-  Update nixpkgs first to support python 3.10

refac(back): #885 update nixpkgs

---

README.md
src/args/agnostic.nix
src/args/make-secret-for-aws-from-gitlab/default.nix
src/args/make-secret-for-aws-from-gitlab/template.sh
src/evaluator/modules/default.nix
src/evaluator/modules/secrets-for-aws-from-gitlab/default.nix

- Add builtin for assuming aws sessions using
GitLab OIDC

feat(cross): #889 secrets for aws from gitlab

---

README.md

fix(docs): #892 fix documentation

---

src/cli/main/__main__.py

- This way its integrity is guaranteed
- Polish a little bit the logs

feat(back): #894 hash the provenance

---

docs/src/security/slsa.md

- Document SLSA build requirements

feat(doc): #901 document build reqs

---

docs/book.toml
docs/src/SUMMARY.md
docs/src/security/README.md
docs/src/security/slsa.md

- Document SLSA common requirements

feat(doc): #901 common reqs

---

README.md
src/args/agnostic.nix
src/args/secure-kubernetes-with-rbac-police/default.nix
src/args/secure-kubernetes-with-rbac-police/entrypoint.sh
src/evaluator/modules/default.nix
src/evaluator/modules/secure-kubernetes-with-rbac-police/default.nix

- Add secure kubernetes with rbac police arg

feat(back): #909 secure kubernetes

---

.reuse/dep5
LICENSES/MIT.txt
makes/license/entrypoint.sh
makes/license/main.nix

- Add licensing information and enable the reuse linter

feat(cross): #0 lint with reuse

---

.github/workflows/dev.yml
.github/workflows/prod.yml

- Add a job to the CI/CD that verifies we comply the reuse specification

feat(build): #0 add license job

---

docs/src/SUMMARY.md
docs/src/governance/README.md

- Add a small text defining who takes decisions in the project and what their roles are

feat(doc): #919 governance model

---

README.md
docs/book.toml
docs/src/SUMMARY.md
docs/src/contributing/README.md

- Add a small text explaining the contribution process and the DCO

feat(doc): #919 dco

---

docs/.gitignore
docs/book.toml
docs/mermaid-init.js
makes.nix
makes/docs/entrypoint.sh
makes/docs/main.nix

feat(doc): #919 mermaid support

---

docs/src/architecture/README.md

feat(doc): #919 sub graphs arch

---

LICENSES/MIT.txt.license
docs/src/SUMMARY.md
docs/src/security/assurance.md

- Start practicing software assurance by using the methodology proposed by NIST
- Add one claim, with one proof

feat(build): #919 software assurance

---

src/args/lint-with-ajv/ajv-cli/package-lock.json
src/evaluator/modules/format-markdown/doctoc/package-lock.json

- Upgrade all deps, not only minimist

feat(build): upgrade deps

---

docs/src/security/assurance.md

- Add a few other assurance cases regarding the python code of the CLI

feat(doc): #919 more assurance cases

---

docs/src/security/threat-model.md

- Document one tampering threat

feat(doc): #919 tampering threat

---

.github/workflows/prod.yml
.gitlab-ci.yaml
README.md
makes.nix
makes/main.nix
src/cli/main/cli.py
src/evaluator/modules/pipelines/default.nix

- 22.10 is now the stable release
- 22.11 is now the unstable release

feat(cross): #0 bump to 22.11

---

.buildkite/pipeline.yml

- Add additional steps for testing purposes
Signed-off-by: Daniel Salazar <dsalazar@fluidattacks.com>

feat(build): #960 additional steps

---

.buildkite/pipeline.yml

- Migrate dev pipeline to buildkite

feat(build): 960 dev pipeline

---

.mailmap
src/args/make-node-js-modules/builder.sh

- allow bin to be empty as some packages require it
Closes #967

fix(build): #967 nodejs binaries

---

flake.lock
flake.nix

- Provide makes for many systems

refac(cross): #0 cross system

---

README.md
flake.nix
src/args/agnostic.nix
src/args/make-workspace-for-terraform-from-env/default.nix
src/args/make-workspace-for-terraform-from-env/template.sh
src/evaluator/modules/default.nix
src/evaluator/modules/workspace-for-terraform-from-env/default.nix

- Add builtin for supporting tf workspaces
- Add doc

feat(back): #981 tf workspaces

---

makes.nix
src/args/lint-python/pypi-deps.yaml
src/args/lint-python/pypi-sources-3.10.yaml
src/args/lint-python/pypi-sources-3.11.yaml
src/args/lint-python/pypi-sources-3.8.yaml
src/args/lint-python/pypi-sources-3.9.yaml

- Update testPython example to 3.11
- Update lintPython pypi dependencies
Signed-off-by: Daniel Salazar <podany270895@gmail.com>

feat(back): #985 update lint python builtin

---

README.md
src/args/fetch-rubygem/default.nix
src/args/make-ruby-gems-environment/default.nix
src/args/make-ruby-gems-install/default.nix

- Make makeRubyGemsEnvironment support sources
- Make makeRubyGemsInstall support sources
- Update fetchRubyGem
- Update doc
Signed-off-by: Daniel Salazar <podany270895@gmail.com>

feat(back): #997 support sources

---

makes/container-image/main.nix

- Add grep to container for better GitLab CI support

feat(build): #1003 add grep to container

---

.github/workflows/prod.yml
README.md
makes.nix
makes/main.nix
src/cli/main/cli.py
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

- Add support for latest tag and container
- Update doc

feat(build): #1013 latest tag

---

README.md

- Improve versioning documentation

feat(doc): #1013 improve versioning

---

.mailmap
README.md
makes.nix
makes/cli/env/runtime/main.nix
src/cli/main/cli.py
src/evaluator/modules/cache/default.nix

- make the cache module generic
- add priority to use the different caches
- add cache server type
- by default the server only read the cache, it must be specified that the cache is also written

refac(back): #1007 redefine cache module

---

README.md

- Made installation and usage sections simpler
- Remove CI/CD providers comparison
- Add documentation for configuring caches on multi-user installations

feat(doc): #1005 simpler doc

---

docs/mkdocs.yaml

- Set remote branch for gh pages deployment

feat(build): #940 set remote branch

---

docs/mkdocs.yaml

- As envs get automatically created
- Forks can now create their own github pages by running the deploy job

feat(build): #940 use default branch

---

docs/mkdocs.yaml
docs/src/makes-nix-reference.md

- Migrate makes nix reference
- Considerably reduce external links for simplicity

feat(doc): #940 makes nix reference

---

README.md
docs/src/index.md

- Remove periods from table items

refac(doc): #940 rm periods

---

docs/mkdocs.yaml

feat(doc): #940 night mode

---

.github/workflows/prod.yml
README.md
docs/.gitignore
docs/mkdocs.yaml
makes/docs/deploy/entrypoint.sh
makes/docs/deploy/main.nix
makes/docs/dev/entrypoint.sh
makes/docs/dev/main.nix

- Set custom domain
- Separate dev and deploy jobs

feat(doc): #940 custom domain

---

docs/mkdocs.yaml
docs/src/getting-started.md

- Improve installation doc
- Add extra plugins
- Add external links

feat(doc): #940 improve installation

---

docs/src/api/builtins/database.md
docs/src/api/builtins/deploy.md
docs/src/api/builtins/development.md
docs/src/api/builtins/environment.md
docs/src/api/builtins/examples.md
docs/src/api/builtins/format.md
docs/src/api/builtins/framework-configuration.md
docs/src/api/builtins/index.md
docs/src/api/builtins/lint.md
docs/src/api/builtins/monitoring.md
docs/src/api/builtins/performance.md
docs/src/api/builtins/secrets.md
docs/src/api/builtins/security.md
docs/src/api/builtins/test.md
docs/src/api/builtins/utilities.md
docs/src/getting-started.md

- Add code sections to all builtins
- Use admonitions for notes and warnings

feat(doc): #940 code sections

---

.github/workflows/prod.yml
docs/src/api/builtins/database.md
docs/src/api/builtins/index.md
docs/src/api/extensions/format-conversion.md
makes/docs/deploy/entrypoint.sh

- Push gh-pages versions with technology

feat(build): #940 push with technology

---

makes/docs/deploy/entrypoint.sh

fix(build): #940 use right flag

---

.github/workflows/prod.yml
docs/src/getting-started.md
makes/docs/deploy/entrypoint.sh

- Improve examples in getting started section
- Simplify deploy

feat(doc): #940 improve examples

---

docs/src/contributing.md

feat(doc): #940 contributing title

---

src/nix/sources.json

- Some packages are now updated to be used in macOs
- Update nixpkgs reference

refac(back): #1045 update nixpkgs

---

src/evaluator/modules/format-python/default.nix
src/evaluator/modules/format-python/settings-black.toml

- Update `formatPython` packages to use python 3.9

refac(back): #1059 update formatpython

---

src/cli/main/cli.py

- Change cachix compression level from 0 to default (2)

refac(back): #1059 change cache compression

---

.github/workflows/prod.yml
docs/src/api/builtins/deploy.md
makes.nix
makes/docs/deploy/entrypoint.sh
src/args/deploy-container-image/default.nix
src/args/deploy-container-image/entrypoint.sh
src/args/make-dynamodb/entrypoint.sh
src/args/make-script/template.sh
src/args/make-secret-for-aws-from-env/template.sh
src/args/make-secret-for-aws-from-gitlab/template.sh
src/args/make-secret-for-kubernetes-config-from-aws/template.sh
src/args/shell-commands/template.sh
src/evaluator/modules/deploy-container-image/default.nix

- Add oidc signing capabilities to deployContainer builtin
- Sign makes containers using OIDC with GitHub actions

feat(back): #1011 sign container

---

.github/workflows/prod.yml
makes.nix
src/args/lint-nix/default.nix
src/evaluator/modules/lint-nix/default.nix

- Use buildjet arm runners for building arm containers

feat(build): #1064 buildjet arm runners

---

.github/workflows/dev.yml
.github/workflows/prod.yml

- Update linux nixos container
- Move arm jobs to arm nixos container

feat(build): #1064 update nixos container

---

.github/workflows/dev.yml
.github/workflows/prod.yml
.github/workflows/scorecards-analysis.yaml
docs/src/getting-started.md
src/nix/sources.json

- Update internal nixpkgs to validate if skopeo hanging on arm is solved

feat(build): #1064 update nixpkgs

---

.github/workflows/prod.yml
docs/src/getting-started.md
makes.nix
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

- Sign containers as they are deploying now
- Use smaller buildjet machines
- Update container registry references
- Update pipeline builtin to support images

feat(build): #1064 sign arm containers

---

docs/src/getting-started.md

feat(doc): #1064 update container registry

---

makes/container-image/main.nix

- Add getconf to container to allow some software to
retrieve data type sizes

feat(infra): #1064 getconf

---

src/args/make-python-pypi-environment/default.nix

- Add cython to build env when bootstrapped as it is sometimes needed

feat(back): #1083 cython to build env

---

.github/workflows/dev.yml
.mailmap
docs/src/api/builtins/test.md
makes.nix
src/args/agnostic.nix
src/args/test-pull-request/default.nix
src/args/test-pull-request/entrypoint.sh
src/args/test-pull-request/package-lock.json
src/args/test-pull-request/package.json
src/evaluator/modules/default.nix
src/evaluator/modules/test-pull-request/default.nix

- Add builtin
- Add job to dev pipeline

feat(build): #1092 test pull request builtin

---

docs/src/api/builtins/test.md

- Improve test pr documentation

feat(doc): #1092 test pr

---

docs/src/api/builtins/test.md

feat(doc): #1092 test pr doc

---

.github/workflows/prod.yml
docs/src/api/builtins/utilities.md
docs/src/getting-started.md
docs/src/versioning.md
makes.nix
makes/main.nix
src/cli/main/cli.py
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

- Deploy new makes version that includes new CLI optimization
- Update doc
- Update pipelines
- Update containers

feat(cross): #1101 new makes version

---

.github/workflows/prod.yml
docs/src/api/builtins/utilities.md
docs/src/getting-started.md
docs/src/versioning.md
makes.nix
makes/main.nix
src/cli/main/cli.py
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

- Release new monthly version 23.07
- Pin 23.06

feat(back): #1122 new monthly version

---

docs/src/api/builtins/lint.md
docs/src/getting-started.md

fix(doc): #1130 broken links

---

src/args/make-python-pypi-environment/default.nix

- retry up to 3 times on curl errors.

feat(build): #1126 retry makepythonpypienvironment

---

docs/mkdocs.yaml
docs/overrides/404.html

- override 404 html page to redirect to main page

feat(build): #1135 fix url redirection

---

makes/docs/runtime/pypi/sources.yaml

- update sources to solve vulnerabilities

feat(build): #1142 update pypi sources

---

src/args/lint-git-commit-msg/commitlint/package-lock.json
src/args/lint-with-ajv/ajv-cli/package-lock.json
src/args/test-pull-request/package-lock.json

- update package-lock.json file to solve vulnerabilities

feat(build): #1139 update package-lock.json

---

makes/container-image/main.nix

- Replace inputs.nixpkgs with __nixpkgs__ at container-image

feat(build): #1097 deprecate inputs.nixpkgs

---

.github/workflows/dev.yml
.github/workflows/prod.yml

Upgrade install-nix-actions to V22

feat(build): #1123 upgrade install-nix-actions

---

src/args/lint-with-ajv/ajv-cli/package-lock.json
src/args/lint-with-ajv/ajv-cli/package.json

- Update fast-json-patch version

feat(build): #1157 update vuln dependencies

---

src/cli/main/cli.py

- Solve excessive privileges to temporary files
- Creates a temporary file in the most secure manner possible.

feat(build): #1159 excessive privileges

---

.github/workflows/prod.yml

- fix git config safe.directory error

feat(build): #979 fix git config error

---

makes/cli/env/test/pypi-sources.yaml

- Upgrade pytest and pytest-cov

feat(build): #1174 deprecate py

---

makes/cli/env/runtime/pypi/pypi-sources.yaml

- Upgrade pygments vulnerable version

feat(build): #1177 upgrade pygments version

---

.mailmap
makes/cli/env/runtime/pypi/pypi-sources.yaml

- Revert pygments version upgrade, it's necessary code refac due to dependencies upgrades
- Fix mailmap lint

feat(build): #1177 revert upgrade pygments version

---

src/args/manage-ports/template.sh

- Fix uncontrolled infinite loop at `wait_for_tcp` function

feat(build): #1002 fix infinite loop

---

makes/docs/runtime/pypi/deps.yaml
makes/docs/runtime/pypi/sources.yaml

- Upgrade mkdocs-material version to solve urllib vuln.

feat(build): #1180 upgrade mkdocs-material version

---

README.md

- Added Total lines of code badge to README

feat(doc): #1184 add loc count badge

---

makes/docs/runtime/pypi/deps.yaml
makes/docs/runtime/pypi/sources.yaml

- Upgrade mkdocs material version to solve urllib vuln

feat(build): #1186 upgrade mkdocs material version

---

docs/src/getting-started.md

- Upgrade getting started tip.

feat(docs): #1190 upgrade getting started tip

---

makes/cli/env/runtime/pypi/pypi-sources.yaml

- add exclusion for pygments vuln

feat(build): #1177 add exclusion for pygments vuln

---

src/args/lint-git-commit-msg/commitlint/package-lock.json
src/args/lint-git-commit-msg/commitlint/package.json

- Upgrade commitlint version to solve dependencies vulns

feat(build): #1195 upgrade commitlint version

---

.mailmap
src/args/lint-python/pypi-sources.yaml

- Upgrade pypi-deps on lint-python linter

feat(build): #1210 upgrade dependencies

---

src/nix/sources.json

- update nixpkgs version to 23.05

feat(build): #1202 fix nixpkgs version

---

makes/main.nix
src/cli/main/cli.py
src/evaluator/default.nix
src/nix/sources.json

- Pin nix version to 2.15 as it looks like 2.16 brings breaking changes for current back pinning method
- Stop supporting nix unstable as it is broken and no being used
- Update nixpkgs to support latest nodejs version

feat(back): #1202 pin nix version

---

makes.nix

- Use right version for amd64 container

fix(build): #1202 right version

---

src/nix/sources.json

- Uprade nixpkgs to support latest nodejs version

feat(build): #1202 upgrade nixpkgs

---

docs/src/api/extensions/python.md
src/args/agnostic.nix
src/args/make-python-environment/default.nix

- Add makePythonEnvironment builtin

feat(back): #1171 make python environment

---

docs/src/api/builtins/utilities.md
makes/utils/makePythonLock/entrypoint.sh
makes/utils/makePythonLock/main.nix

- Update util to generate poetry locks
- Considerably simplify it

feat(back): #1171 update make python lock

---

makes/container-image/main.nix
makes/utils/makeRubyLock/main.nix

- Pin nix in container
- Pin nix in makeRubyLock

refac(build): #1171 pin nix versions

---

makes/utils/makeNodeJsLock/main.nix

- Deprecate `makeNodeJsVersion` from `makeNodeJsLock`

feat(back): #1249 deprecate makenodejsversion

---

src/args/agnostic.nix
src/args/make-node-js-version/default.nix

- Remove makeNodeJsVersion from `agnostic.nix`
- Delete `make-node-js-version` folder

feat(back): #1249 rm makenodejsversion

---

src/args/secure-python-with-bandit/poetry.lock
src/args/secure-python-with-bandit/pyproject.toml

feat(back): #1256 update gitpython to 3.1.41

---

src/args/make-python-pypi-environment/default.nix

Deprecate `makePythonVersion` from
`makePythonPypiEnvironment`

feat(back): #1249 deprecate makepythonversion

---

src/args/agnostic.nix
src/args/make-python-version/default.nix

- Remove `makePythonVersion` from `agnostic.nix`
- Delete `make-python-version` builtin

feat(back): #1249 rm makepythonversion

---

makes/utils/makeRubyLock/main.nix

- Deprecate `makeRubyVersion` from `makeRubyLock`

feat(back): #1249 deprecate makerubyversion

---

makes/docs/runtime/pypi/poetry.lock
makes/docs/runtime/pypi/pyproject.toml

- Update jinja2 to 3.1.3 to solve vuln

feat(build): #1266 update jinja2 to 3.1.3

---

.github/workflows/prod.yml
docs/src/api/builtins/utilities.md
docs/src/getting-started.md
docs/src/versioning.md
makes.nix
makes/main.nix
src/cli/main/cli.py
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

feat(back): #1171 new release

---

src/args/make-ruby-gems-environment/default.nix

- Add `__nixpkgs__` to `makeRubyGemsEnvironment`.

feat(back): #1249 add nixpkgs to makerubygemsenvironment

---

docs/src/api/extensions/node.js.md
src/args/lint-git-commit-msg/commitlint/package-lock.json
src/args/lint-git-commit-msg/default.nix
src/args/lint-with-ajv/default.nix
src/args/make-node-js-modules/builder.sh
src/args/test-pull-request/default.nix
src/evaluator/modules/format-markdown/default.nix

- Adapt makeNodeJsModules to support node 20 and 21
- Upgrade all builtins

feat(back): #1273 upgrade to node 21

---

.mailmap
docs/src/api/builtins/utilities.md
makes/utils/makePythonLock/entrypoint.sh
makes/utils/makePythonLock/main.nix

- added python version as argument for makePythonLock
- modified docs with latest feature
- added user to mailmap

feat(build): #1275 python version in lock

---

docs/src/api/builtins/utilities.md

- minox fix in typo for makePythonLock

fix(doc): #1275 typo

---

src/args/compute-on-aws-batch/batch-client/build/deps/fa_purity.nix
src/args/compute-on-aws-batch/batch-client/pyproject.toml
src/nix/sources.json

- update nixpkgs to latest version

feat(build): #1278 update nixpkgs

---

docs/mkdocs.yaml

- fix url to avoid redirection

fix(doc): #1283 url

---

src/args/make-node-js-modules/default.nix

- added git binary to enable node2nix to fetch deps from git repos

feat(build): #860 node2nix from git repos

---

src/args/make-python-environment/default.nix

- Minor refactors to make-python-environment builtin for clarity

refac(back): #1282 minor refactors

---

src/args/lint-python/builder.sh
src/args/lint-python/poetry.lock
src/args/lint-python/pyproject.toml

- Use dmypy instead of mypy to run type checking
- Update mypy to 1.8.0

feat(build): #1298 use dmypy

---

src/args/lint-python/builder.sh

rever(build): #1298 remove dmypy usage

---

src/args/lint-python/builder.sh

- Use dmypy instead of mypy to improve the performance

feat(build): #1298 use dmypy instead of mypy

---

docs/mkdocs.yaml

- for seo issues the name of the site should be more descriptive

fix(doc): #1304 change site name

---

makes/docs/runtime/pypi/poetry.lock
makes/docs/runtime/pypi/pyproject.toml

Pin idna version to solve vuln dep issue

feat(doc): #1320 update idna version

---

makes/docs/runtime/pypi/poetry.lock
makes/docs/runtime/pypi/pyproject.toml

feat(doc): #1322 update deps

---

makes/docs/runtime/pypi/poetry.lock
makes/docs/runtime/pypi/pyproject.toml

Update requests to `2.32.2` version

feat(doc): #1325 update requests

---

docs/src/getting-started.md

- Update the GitHub Actions example in the Getting Started guide to show the use of
`chown -R root:root /github/workspace`

feat(doc): #1328 update github actions example

---

makes/docs/runtime/pypi/poetry.lock
makes/docs/runtime/pypi/pyproject.toml

- Upgrade `mkdocs-material` from `9.5.3` to `9.5.25`

feat(doc): #1230 upgrade mkdocs material

---

makes/docs/runtime/pypi/poetry.lock
makes/docs/runtime/pypi/pyproject.toml

- Update urllib3 from 2.2.1 (vulnerable) to 2.2.2

feat(back): #1341 update vuln depencency

---

docs/src/api/extensions/python.md
src/args/agnostic.nix
src/args/make-python-environment/default.nix
src/args/make-python-poetry-environment/default.nix
src/evaluator/modules/cache/default.nix

- Add makePythonPoetryEnvironment builtin
- Make makePythonEnvironment use such builtin
- deprecate listOptional

feat(back): #1345 make python poetry environment

---

src/cli/main/cli.py
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

- Increase git depth to 3 for better compatibility
- Deprecate gitDepth in favor of variables

feat(back): #1355 increase git depth

---

.github/workflows/prod.yml
docs/src/api/builtins/deploy.md
makes.nix
src/args/agnostic.nix
src/evaluator/modules/deploy-container-image/default.nix

- Rename from deployContainerImage to deployContainer

refac(back): #1351 simplify builtin name

---

docs/src/api/builtins/deploy.md
src/args/agnostic.nix
src/args/deploy-container-manifest/default.nix
src/args/deploy-container-manifest/entrypoint.sh
src/evaluator/modules/default.nix
src/evaluator/modules/deploy-container-manifest/default.nix

feat(back): #1351 deploy container manifest

---

src/args/lint-terraform/entrypoint.sh
src/evaluator/modules/lint-terraform/config.hcl
test/terraform/module/main.tf

- Add tflint to the lint-terraform built-in

feat(back): #1381 use tflint

---

.mailmap
src/args/lint-git-commit-msg/commitlint/package-lock.json

- Update coss-spawn to 7.0.3 to 7.0.6

feat(back): fluidattacks#1334 update cross-spawn version

---

.github/workflows/prod.yml
docs/src/api/builtins/deploy.md
docs/src/api/builtins/utilities.md
docs/src/getting-started.md
docs/src/versioning.md
makes.nix
makes/main.nix
src/cli/main/cli.py
src/evaluator/modules/pipelines/default.nix
test/pipelines/.gitlab-ci.yaml

- Add new 24.12 pre-release version
- Make 24.09 stable version

feat(cross): #1378 new version

---

makes/container-image/main.nix

- Add nix-ld to container image in order to provide
dynamic linking libraries
on non-nix binaries

feat(build): #1388 nix-ld to container image

---

src/evaluator/modules/jobs/default.nix

- Force jobs to begin with / for currently CLI compatibility

feat(back): #1223 enforce root jobs

---

.mailmap
docs/poetry.lock
docs/pyproject.toml

feat(back): #1334 update jinja2 version

---

docs/poetry.lock
docs/pyproject.toml

feat(back): fluidattacks#1430 update jinja2 version
